### ISSUE TITLE
Selector that return multiple nodes

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#103]
Hi everyone, 
I'm trying to do the following.
I have an example model:

```
class user{
    private name:string;
    get id(){
        return this.name;
    }

    set id(value){
        this.name = value;
    }
}
```

then in my UI I have a table that has a multiple rows with user data, so I use the following selector:

```
 static RowTable = Target.the('Row table')
    .located(by.css('div.user-table'));
```

this locator returns multiple targets, so I need to access to these multiples targets to get the name text and assign to my model, but I'm not sure how to manage multiple results using serenity.

can you help me with this?

thanks

**Comment by jan-molak** [comment]
Hey @jdmesalosada , could you please post an example of the test scenario you're trying to implement?

Thanks!

Ps. I've corrected the formatting of the code samples above, please have a look at [Creating and Highlighting Code Blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) when posting additional samples as that correct formatting greatly improves readability.

**Comment by jdmesalosada** [comment]
Hi @jan-molak thanks for the tool. 
This is an example  of my scenario. My idea is capture the information from the UI, and then that information will be mapped to a model class so I can make the assertion more readable:

```
export class Movements implements Question<PromiseLike<ProductMovement[]>> {

    static found = () => new Movements();
	
	    setProductMovement(info: string[]): ProductMovement {
        //set the properties according with the text captured from the UI. 
        return productMovement;
    }

    answeredBy(actor: UsesAbilities): PromiseLike<ProductMovement[]> {
        const setInfo = this.setProductMovement;
        const productMovements: Array<ProductMovement> = new Array<ProductMovement>();
        return Text.ofAll(DbProductMovementsWo.Movements).answeredBy(actor)
            .then(function (movementList) {
                movementList.forEach(function (element, index) {
                    productMovements.push(setInfo(movementList[index].split('\n')));
                });
                return productMovements;
            });
    };
}


export class ProductMovement {
//here setters and getters
}
```

Thanks.

**Comment by jan-molak** [comment]
Ah, I see, thanks for the explanation! Please let me know if [this example](https://github.com/serenity-js/tutorial-journey-planner/blob/ce1e6f84cce33a4052b6d0e9610a95e1282d7109/src/journey_planner/journeys_found.ts) provides you with an answer to your question.

Best,
Jan

**Comment by jdmesalosada** [comment]
Yes, I used that example and it works thanks.
