### ISSUE TITLE
Question: When debugging, how can i resolve a Question?

### ISSUE THREAD

**Issue by BlacktoBlue** [jan-molak/serenity-js#106]
I am trying to debug my tests in particular:

`See.if(ClientLookup.All_Clients, containsMembers(this.clientList))`
ClientLookup.All_Clients is 
`static All_Clients: Question<PromiseLike<string[]>> = Text.ofAll(ClientLookup.List_Of_All_Clients)`
and containsMembers is 
`expected => actual => expect(actual).to.eventually.contain.members(expected)`
using Chai

When it run I get AssertionError: expected [ Array(30) ] to be a superset of [ Array(30) ]

So I am trying to debug it and this.clientList I can easily output to the console as it is plain array. But i need to know if there is a way to output the Resolved Question so I can output it to the console. When I use `ClientLookup.All_Clients.toString()`  I get `the List of all clients`

**Comment by jan-molak** [comment]
You could try to create a wrapper around the question that outputs the result of the wrapped question:

```typescript
const Debug = <T>(question: Question<PromiseLike<T>>) => Question.where<PromiseLike<T>>(`debug output of ${question}`, actor => {
    const answer: PromiseLike<T> = question.answeredBy(actor);

    return answer.then(value => console.log(value)).then(() => answer);
});
```

Please let me know if that helps?

Jan

**Comment by BlacktoBlue** [comment]
This works like a charm. My typescript isn't brilliant so I dont fully understand quite what it is doing but it is outputting what i Need.

Cheers

**Comment by BlacktoBlue** [comment]
Just updated to latest version of Serenity and now Question does not have a property of where. Is there an alternative?

**Comment by jan-molak** [comment]
Yes, apologies for that, I've changed the api from `Quetion.where` to `Question.about`; `Question.where` was a mistake, should've been `about` in the first place.
