### ISSUE TITLE
Capitalisation in test case title in Reports

### ISSUE THREAD

**Issue by hudson-t** [jan-molak/serenity-js#107]
When you go to a test case page within the reports, the title appears to have the first letter of every word capitalised:

![image](https://user-images.githubusercontent.com/26221061/31892470-01bbb1a8-b801-11e7-8bd1-b185fe5e8208.png)

This is a minor problem but it isn't consistent and isn't really correct!

**Comment by jan-molak** [comment]
The HTML report is produced by [Serenity BDD](http://serenity-bdd.info/#/), so if you believe this to be an error could I ask you to raise a ticket against the [serenity-bdd/serenity-core](https://github.com/serenity-bdd/serenity-core) project?

Thanks!
Jan

**Comment by nbarrett** [comment]
I've been meaning to raise a ticket in [core](https://github.com/serenity-bdd/serenity-core) about this one for a while @hudson-t! I agree, that it would be better to leave the case of the title as-is do you think?

**Comment by hudson-t** [comment]
@jan-molak, @nbarrett - I have now raised this issue against https://github.com/serenity-bdd/serenity-core/issues/981

**Comment by Tom-Hudson** [comment]
@nbarrett, @jan-molak - #981 is now closed and merged. Hopefully this will be in the next release :smile:
