### ISSUE TITLE
Feature Request: Format of mocha tests in the console

### ISSUE THREAD

**Issue by Tom-Hudson** [jan-molak/serenity-js#108]
Currently, the 'Feature level' description ('Authentication' in this case) of a mocha based test is prefixed to the front of each test:

```
  √ Authorisation Logging in with invalid credentials shows an error message and clears the username and password fields: 3392ms
  √ Authorisation Logging in with an invalid password shows an error message and clears the username and password fields: 3161ms
  √ Authorisation Logging in with a blank username shows an error on the password field: 1511ms
  √ Authorisation Logging in with a blank password shows an error on the password field: 1541ms
  √ Authorisation Logging in with valid credentials takes you to the dashboard page: 3066ms
```
It would be better if the Feature was instead logged once, and each test was output below it like so:

```
Authorisation
  √ Logging in with invalid credentials shows an error message and clears the username and password fields: 3392ms
  √ Logging in with an invalid password shows an error message and clears the username and password fields: 3161ms
  √ Logging in with a blank username shows an error on the password field: 1511ms
  √ Logging in with a blank password shows an error on the password field: 1541ms
  √ Logging in with valid credentials takes you to the dashboard page: 3066ms
```

This would make it more consistent with the Serenity BDD report, and it makes it a lot more readable!

**Comment by jan-molak** [comment]
The console output is generated by Mocha, so isn't it just the case of switching from `list` reporter to `spec` reporter? Here are some [Mocha docs](https://mochajs.org/#reporters) that might be useful.

Please let me know if that helps.

Jan

**Comment by Tom-Hudson** [comment]
@jan-molak - I guess didn't clock that mocha was doing the console logging. I need to take a look at the code for Serenity/JS and see how it all stitches together.

Switching to the `spec` reported outputs the below, which is closer to where I want it to be, but not quite 100%. I will probably take a look into creating a custom reporter to only put the 'Feature level' description block on it's own line - but a quick look into what's available with mocha, this might not be possible.

```
  Authorisation
    Logging in
      with invalid credentials
        √ shows an error message and clears the username and password fields (3324ms)
      with an invalid password
        √ shows an error message and clears the username and password fields (3156ms)
      with a blank username
        √ shows an error on the password field (1498ms)
      with a blank password
        √ shows an error on the password field (1592ms)
      with valid credentials
        √ takes you to the dashboard page (3372ms)
```

**Comment by jan-molak** [comment]
I think a [custom reporter](https://github.com/mochajs/mocha/wiki/Third-party-reporters) based on the [`spec` reporter](https://github.com/mochajs/mocha/blob/master/lib/reporters/spec.js) should not be too hard to implement.

Hope that helps!
Jan
