### ISSUE TITLE
TextOfAll function is not  waiting for the elements being displayed -Angular 4

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#109]
Hi, I'm using the function TextOfAll in order to capture the texts from multiple elements, but I'm seeing this function is not waiting until the elements are present or visible instead the function is returning a empty array. So I copy the source code of the function in my code, and I can see the error, that says the element specified was not found.
I created a new function in order to wait, but I would like to know it is possible make the adjust in the principal function . I'm not sure if getText promise is not working due I'm using Angular 4:

```
export class TextOfAll implements Question<PromiseLike<string[]>> {
  answeredBy(actor: UsesAbilities & PerformsTasks): PromiseLike<string[]> {
    const target = this.target;
    return actor.attemptsTo(Wait.upTo(Duration.ofMillis(config.get('timeOuts.elementLoad')))
      .until(this.target, Is.present())).then(function () {
        const elementTexts = BrowseTheWeb.as(actor).locateAll(target).getText() as any;
        return elementTexts;
      });
  }

  constructor(private target: Target) {
  }

  toString = () => `the text of all ${this.target}`;
}
```

**Comment by jan-molak** [comment]
That's an interesting point. Should every single call to `TextOfAll` actually wait for the element to be present?

I personally prefer to have explicit synchronisation points (check out [Joes's blog entry](https://www.joecolantonio.com/2014/04/01/the-1-killer-of-selenium-script-performance-and-reliability/) on this subject).

So if I wanted to always wait for an element to be present before performing a specific assertion, I'd:
- create a custom task that describes the assertion
- make it wrap the `Wait.unti` as well as the assertion

For example:

```typescript
const CheckIfProductHasBeenAddedToTheBasket = () => Task.where(`#actor checks if the product has been added to the basket`,
    Wait.upTo(Duration.ofMillis(config.get('timeOuts.elementLoad'))),
    See.if(Text.of(.....), equals(.....)),
)
```

Then in your test:

```typescript
actor.attemptsTo(
    AddProductToTheBasket(),
    CheckIfProductHasBeenAddedToTheBasket(),
);
```

Please let me know if that helps.

Best,
Jan

**Comment by jdmesalosada** [comment]
Ah ok excellent I will try that. Thanks.
