### ISSUE TITLE
Unable to Input value into a dropdown

### ISSUE THREAD

**Issue by srinivasbudh** [jan-molak/serenity-js#11]
Hi Jan,

First of all thank you for closing the issue [7](https://github.com/jan-molak/serenity-js/issues/7). I was trying to explore and find how to enter the value into a drop down using a task. 

I tried using below syntax it didn't work,
`Enter.theValue(XX).into(XXX)`  

Also It would be of great help if you can suggest how to clear the data which is already in input box(I mean something to suport driver.findElementby(XXX).clear())

**Comment by nbarrett** [comment]
You could use `Select.theValue('France').from(SingleCountry.Selector)`?

**Comment by srinivasbudh** [comment]
@nbarrett:  Thanks, Sorry for the trouble Closing this now.

To clear I'm using Clear.theValueof();

**Comment by jan-molak** [comment]
Hey guys, yes, `Select` is the way to do it :-) Check out the [html form recipe](https://github.com/jan-molak/serenity-js/blob/master/spec/cookbook/html_form.recipe.ts) from the "[cookbook](https://github.com/jan-molak/serenity-js/tree/master/spec/cookbook)" test suite.
