### ISSUE TITLE
Feature Request: Add method to get current URL to the Website Question

### ISSUE THREAD

**Issue by Tom-Hudson** [jan-molak/serenity-js#111]
At the moment, there doesn't appear to be a Question that ships with Serenity/JS to check a URL value.

Enhancing the Website Question to have a static method of 'url', which uses a new `getCurrentUrl` in the `BrowseTheWeb` ability would be logical to me.

**On a side note...**
_I really want to PR this myself but I am having issues with dependencies before I have even started making a change. I have ran `npm install` and expected it to just work - am I missing something? I only spent a few minutes on trying to get it built the other night so I will give it another go when I can. I really want to contribute! There are a few issues I think I could knock out relatively quickly._

**Comment by jan-molak** [comment]
That's great, thanks for offering your help! Your approach makes perfect sense.
I'd also add a test to [the content recipe](https://github.com/jan-molak/serenity-js/blob/f66fc0b7c8a292e57fb43ef0e852739c3675fbe3/packages/serenity-js/spec/cookbook/content.recipe.ts);

**RE side note**:

You should be able to run `npm install` and `npm run verify` to run the full build. Please note that you'll need to use node 6 as some of the dependencies are not yet fully compatible with node 8. Please let me know if you encounter any problems and I'll try to help.

**Comment by Tom-Hudson** [comment]
@jan-molak - Just finished the PR for this. 

**Another side note**
I did still have issues building. Didn't affect me implementing this change though!

After running `npm install`, all seemed well. But when I ran `npm run verify`, things went wrong. The `@serenity-js/core` dependencies seem to be missing somehow.

[Here's the output](https://github.com/jan-molak/serenity-js/files/1420257/npm_run_verify_output.txt)

I am running the latest node 6 release as you suggested.

Also, I noticed there is no `package-lock.json` in the repo. Can I suggest you update to npm@5+ so when you run install/update it will generate one so you can commit it. My team had so much trouble in our CI with chained dependencies which had no fixed versions in their package.json. It caused random build errors all the time, but with the new package-lock file, it has eliminated all this!

As I was writing this, the Travis CI build failed with similar errors to me - I am 99.9% sure my changes didn't cause this!

**Comment by jan-molak** [comment]
That is a good suggestion, thanks. I wanted to have npm consistent with the version of node I'm using, so node 6 -> npm 3, node 8 -> npm 5. Either this or move to yarn.

**Comment by Tom-Hudson** [comment]
@jan-molak - There really is no need to keep the npm and node versions in sync. People with npm 3 would still have the same experience they have now, but your CI and people with npm v5 can enjoy the lockfile goodness! 

Moving to npm 5 is the best option in my opinion! Yarn was created to address performance issues and lack of package locking in npm. Version 5+ has addressed both these issues, so Yarn no longer makes as much sense as it did. I do believe however, it is still marginally faster at downloading dependencies and integrity checks than npm.
