### ISSUE TITLE
Select random element.

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#114]
Hi Jan how are you?
 I have a question regarding a locator that returns multiple elements.

For example I have a list of elements, so I create my target, with this target I capture all the elements, but using the target I will be able only to click the first element, I would like to have like a list of target and make a random and select one, and then click it.
I was thinking to use protractor directly to achieve this:

```
const RandomLocator = (result: ElementFinder) => {
  return result.locateAll(myTarget);
}
```

Can you provide some help here.
Thanks.

**Comment by Tom-Hudson** [comment]
@jdmesalosada - You should maybe create a custom interaction for this?

Something like the below:
```
import { Target, UsesAbilities, BrowseTheWeb, Interaction } from "serenity-js/lib/screenplay-protractor";
import { ElementArrayFinder, ElementFinder } from "protractor";

export class ClickARandom implements Interaction {

    public static on(target: Target): ClickARandom {
        return new ClickARandom(target);
    }

    performAs(actor: UsesAbilities): PromiseLike<void> {
        return this.randomElement(BrowseTheWeb.as(actor).locateAll(this.target)).click();
    }

    private randomElement(elements: ElementArrayFinder): ElementFinder {
        return elements[Math.floor(Math.random() * elements.length)];
    }

    constructor(private target: Target) {    }

    toString = () => `{0} click a random ${this.target}`;
}
```
I have not tested this at all but hopefully it works and helps you. This implementation means you can re-use this on any target which has multiple elements.

**Comment by jdmesalosada** [comment]
Hi @Tom-Hudson  thanks for this help, I tried the code but I'm getting the following error:
Promisevoid is not assigble to promiselike void, I was thinking is there is someway to take the ElementFinder and convert it to target, and then use the serenity Click.on 

Thanks

**Comment by Tom-Hudson** [comment]
@jdmesalosada - I have updated the code in my previous comment. I forgot `ElementArrayFinder` isn't actually an array of `ElementFinder` objects :disappointed:. 

Hopefully the code should work now. But if it doesn't let me know and I will have a crack at it when I am not working blind (I don't  have access to test my code at the time of writing this again).

I also renamed the class and method so it reads better when using it in a task, i.e. `ClickARandomItem.from(ToDo.List)`

**Comment by jdmesalosada** [comment]
Hi Tom thanks for this, I try the code but I'm getting the same error so I did this:

 return this.randomElement(BrowseTheWeb.as(actor)
            .locateAll(this.target)).click() as PromiseLike<void>

And it works.

Thank you

**Comment by Tom-Hudson** [comment]
@jdmesalosada  - cool, glad I could help! - sorry for the back and forth, this would have been a lot easier if I had waited until today to test the code before providing it to you... but we got there in the end.

Can this issue be closed now?

**Comment by jdmesalosada** [comment]
yes I'll close it.

Thank you.
