### ISSUE TITLE
First test always fails

### ISSUE THREAD

**Issue by AG0819** [jan-molak/serenity-js#117]
I'm playing around testing a UI and the first test seems to always fail when trying to find the first UI element. All subsequent tests pass finding the element that the first one couldn't. For a few runs I was able to work around it by opening the browser and loading the page myself then running the tests but that no longer seems to work. I also added an assertion to see if the element exists before matching it up with a variable and that doesn't help. Is anyone else experiencing this?

**Comment by jan-molak** [comment]
Could it be a timing issue? Do you need to wait for an element to become available before performing an assertion? For example:

```typescript
actor.attemptsTo(
    Wait.until(Some_Target, Is.present()),
);
```

Here are [some examples](https://github.com/jan-molak/serenity-js/blob/efb655aa29dafd37ee27229f04516ee1d1498b68/packages/serenity-js/spec/cookbook/waiting.recipe.ts#L176) you might find useful.

If that doesn't help, could you please create a simple example demonstrating the issue using one of the project seeds? ([cucumber](https://github.com/serenity-js/seed-cucumber), [mocha](https://github.com/serenity-js/seed-mocha]).

Thanks!
Jan

**Comment by AG0819** [comment]
Sorry for the delayed response that worked perfectly! Thank you
