### ISSUE TITLE
How to use .then(()=>) inside actor abilities   

### ISSUE THREAD

**Issue by srinivasbudh** [jan-molak/serenity-js#12]
Hi Jan/Barret,

Is there any way I can use **.then(()=>)** inside the actor abilities. My issue is I am currently facing some stability issues as I have series of Tasks that are to be performed as a  series I want to use it with then sample code is as below. 

Execute a task after the completion of first task
```typescript
return stage.theActorCalled(name).attemptsTo(
    Start.andNavigateToLoginPage().then(()=> {
        Login.UsingPNRReference(
            testBooking['bookingReference'] || testBooking['eTicket'], 
            testBooking['lastName']
        )
    })  
)
```

or something like Execute the action after completion of an action

```typescript
@performAs(actor: PerformsTasks): PromiseLike<void> {
    if(this.stringValue.length>6&&this.stringValue.startsWith('0')==false) {		
        return actor.attemptsTo(
            Enter.theValue(this.stringValue)
                  .into(LoginPage.User_Name_Input_Box),
            Enter.theValue(this.stringValueTwo)
                  .into(LoginPage.Password_Input_Box).then(() => {
                      Click.on(LoginPage.Login_Button)
                  }),
            Wait.upTo(Duration.ofSeconds(60)).until(ProfilePage.Full_Name, Is.clickable())
        )
    }
    else {}
```

I'm learning with automation using serenityjs, kindly let me know if this is irrelevant here. I can close this

**Comment by jan-molak** [comment]
Hey @srinivasbudh!

No worries, I'm glad that you asked :-) 

All the tasks passed to the `attemptsTo(...)` method are [automatically combined](https://github.com/jan-molak/serenity-js/blob/master/src/serenity/screenplay/actor.ts#L56) into a chain of promises, so in your case instead of:

```typescript
return stage.theActorCalled(name).attemptsTo(
    Start.andNavigateToLoginPage().then(() => {
        Login.UsingPNRReference(
            testBooking['bookingReference'] || testBooking['eTicket'], 
            testBooking['lastName']
        )
    })  
)
```

you should be able to write:

```typescript
return stage.theActorCalled(name).attemptsTo(
    Start.andNavigateToLoginPage(),
    Login.usingPNRReference(
        testBooking['bookingReference'] || testBooking['eTicket'], 
        testBooking['lastName']
    )
)
```

and then in the `Login` task instead of:

```typescript
class Login {

    @step('{0} logs in...')
    performAs(actor: PerformsTasks): PromiseLike<void> {
        return actor.attemptsTo(
            Enter.theValue(this.stringValue)
                 .into(LoginPage.User_Name_Input_Box),
            Enter.theValue(this.stringValueTwo)
                 .into(LoginPage.Password_Input_Box).then(() => {
                     Click.on(LoginPage.Login_Button)
                 }),
            Wait.upTo(Duration.ofSeconds(60)).until(ProfilePage.Full_Name, Is.clickable())
        )
        
        // rest of the code omitted for clarity
    }
}
```

you could write:

```typescript
class Login {

    @step('{0} logs in...')
    performAs(actor: PerformsTasks): PromiseLike<void> {
        return actor.attemptsTo(
            Enter.theValue(this.stringValue)
                 .into(LoginPage.User_Name_Input_Box),
            Enter.theValue(this.stringValueTwo)
                 .into(LoginPage.Password_Input_Box),
            Click.on(LoginPage.Login_Button),
            Wait.upTo(Duration.ofSeconds(60)).until(ProfilePage.Full_Name, Is.clickable())
        )
    }
}
```

I think that the trouble with the stability is caused by a different thing, though.

### Lambda functions `() => {}`

There's a signifficant difference between 
```typescript
() => { Click.on(LoginPage.Login_Button }
```
present in your example, which is an equivalent of:
```typescript
function () {
   Click.on(LoginPage.Login_Button);
}
```

and
```typescript
() => Click.on(LoginPage.Login_Button
```
which means:
```typescript
function () {
   return Click.on(LoginPage.Login_Button);  // please note the _return_ here
}
```

In the first example, the `Click` never gets invoked because it's not included in the promise chain.
Could that be it?

----

I hope that this helps to clear things a bit. If you have any further questions, please feel free to ask :-)

Best,
Jan

**Comment by srinivasbudh** [comment]
Hi Jan,

First of all,Thanks for your detailed explanation, The solution you suggested is exactly What I'm using currently but this is when I was facing a stability issue(Once in 20 to 25 runs I'm facing the issue). I shared this example in Lambda functions because I wanted to use it to fix the stability, as it was throwing a compilation error I raised a issue with example what I was looking to Implement.

If I get into details , we have no issue when Tasks are called in `attemptsTo(...)` 

But actual issue was when I was calling series of interactions,like in belowLogin Task

```
class Login {

    @step('{0} logs in...')
    performAs(actor: PerformsTasks): PromiseLike<void> {
        return actor.attemptsTo(
            Enter.theValue(this.stringValue)
                 .into(LoginPage.User_Name_Input_Box),
            Enter.theValue(this.stringValueTwo)
                 .into(LoginPage.Password_Input_Box),
            Click.on(LoginPage.Login_Button),
            Wait.upTo(Duration.ofSeconds(60)).until(ProfilePage.Full_Name, Is.clickable())
        )
    }
}
```
`LoginPage.Login_Button` is clicked before the `LoginPage.Password_Input_Box`  is filled with required data. So tried using then but faced compilation 

> src\screenplay\tasks\login.ts (26,61): Property 'then' does not exist on type 'Enter'. (2339)
`
This issue  occurred very rarely, However I'm working on something which at most stable so wanted to avoid test failure in all possible ways.

I am not sue, if this is something because of performance of my network or machine.

**Comment by jan-molak** [comment]
Just a thought, but is there anything sophisticated going on with that `LoginPage.Password_Input_Box` that could delay the processing of input? For example, is the app is checking the strength of the password or something like that? Maybe after entering the value of the password you need to wait for some additional condition before clicking on the login button?

**Comment by srinivasbudh** [comment]
Hi Jan
Yes, `LoginPage.User_Name_Input_Box` has some validation before proceeding further. This migt be a possible reason. I have used a workaround using .thenHit which is already available interactions. This is working fine for me now.

`Enter.theValue(cvv)
                .into(bankPage.Card_CVV)
                .thenHit(protractor.Key.ENTER))`
Thanks for your help. closing this.

**Comment by jan-molak** [comment]
Perfect, thanks for letting me know :-)
