### ISSUE TITLE
error related to chromedriver while running serenityjs 

### ISSUE THREAD

**Issue by vijay-kumar-singh** [jan-molak/serenity-js#120]
Hi,
suddenly my serenityjs based application stopped working. I have upgraded macos sierra version 10.13.1
I am getting following error - 
[10:17:16] W/launcher - Ignoring uncaught error WebDriverError: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.13.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.05 seconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'vijays-MacBook-Pro.local', ip: '172.28.175.141', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b), userDataDir=/var/folders/c0/9ycym1_15ng45kpxrm340m9h0000gn/T/.org.chromium.Chromium.1kgoZ9}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=62.0.3202.94, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 1173013ba9fd937106a591f8eb80afb1
[10:17:16] E/launcher - BUG: launcher exited with 1 tasks remaining

Please suggest how to fix.
Regards,
Vijay

**Comment by jan-molak** [comment]
Could be related to your chromedriver version not being compatible with the version of Chrome you're running? See https://stackoverflow.com/questions/40210169/cannot-get-automation-extension-error-with-chrome-54-0-2840-71

**Comment by vijay-kumar-singh** [comment]
fixed by downgrading  chromedriver to 2.33 .
Thank you for your input.
 Closing this issue.
