### ISSUE TITLE
Unable to navigate to the site test fails

### ISSUE THREAD

**Issue by munna73** [jan-molak/serenity-js#121]
16:50:41] I/update - geckodriver: geckodriver-v0.19.1 up to date
(node:985) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:50:42] I/launcher - Running 1 instances of WebDriver
[16:50:42] I/local - Starting selenium standalone server...
[16:50:43] I/local - Selenium standalone server started at http://192.168.1.160:55976/wd/hub
Feature: Add new items to the todo list

    In order to avoid having to remember things that need doing
    As a forgetful person
    I want to be able to record what I need to do in a place where I won't forget about them

  Scenario: Adding an item to a list with other items
(node:985) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: I don't have the ability to BrowseTheWeb, said James sadly.
(node:985) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ✖ Given that James has a todo list containing Buy some cookies, Walk the dog
  - When he adds Buy some cereal to his list
  - Then his todo list should contain Buy some cookies, Walk the dog, Buy some cereal

Failures:

1) Scenario: Adding an item to a list with other items - features/add_new_items.feature:8
   Step: Given that James has a todo list containing Buy some cookies, Walk the dog - features/add_new_items.feature:10
   Step Definition: features/step_definitions/todo_user.steps.ts:13
   Message:
     function timed out after 60000 milliseconds

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)
1m00.004s
[16:51:45] I/local - Shutting down selenium standalone server.
[16:51:45] I/launcher - 0 instance(s) of WebDriver still running
[16:51:45] I/launcher - chrome #01 failed 1 test(s)
[16:51:45] I/launcher - overall: 1 failed spec(s)
[16:51:45] E/launcher - Process exited with error code 1
npm ERR! Test failed.  See above for more details.

**Comment by jan-molak** [comment]
Hi @munna73!

The error `Error: I don't have the ability to BrowseTheWeb, said James sadly.` means that you need to give the `Actor` that ability (as per [the tutorial](http://serenity-js.org/from-scripts-to-serenity/writing-what-you-would-like-to-read.html#interacting-with-the-system)):

```
const James = Actor.named('James').whoCan(BrowseTheWeb.using(protractor.browser));
```

The `UnhandledPromiseRejectionWarning` means that some promise is not returned correctly.
It's usually worth checking if the Cucumber step definition has a return in it:

```
this.Given(`some precondition`, function() {
    return James.attemptsTo(          // the `return` here is important
      // ... perform some tasks
    );
});
```

Hope this helps!
Jan
