### ISSUE TITLE
Support node 8.x

### ISSUE THREAD

**Issue by jan-molak** [jan-molak/serenity-js#122]
Node 8 has recently become an LTS so it's time for Serenity/JS to support it properly.

Looks like the only dependency that we have that doesn't work on Node 8 is stacktrace-js

**Comment by Tom-Hudson** [comment]
@jan-molak - I should also point out that Protractor doesn't officially support node 8 yet. There is an ongoing [issue with the debugger not working](https://github.com/angular/protractor/issues/4307). It mean debugging using `browser.pause()` doesn't work. But everything else does.

However, I have tried running node 8 with Protractor without debugging working and it's like working blind sometimes!

**Comment by jan-molak** [comment]
Thanks for pointing that out @Tom-Hudson!

**Comment by ctaepper** [comment]
are there any plans/eta for this? we started to use serenity and we love it, however, our current project has requirements for node@^8.9.0
