### ISSUE TITLE
automating responsive web layout and component using serenityjs

### ISSUE THREAD

**Issue by WebTestNinja** [jan-molak/serenity-js#127]
Hi,

I am working on test automation for a web application which is responsive and adaptive.
Some component may visible/Hidden based on screen size (Desktop,Tablet and Mobile).

My test cases gets failed when component is not available on some device and get pass when visible in other device.
For example, Menu component have different display behaviour for desktop and mobile view.

I would like to put some condition in my cucumerjs scenario or serenityjs code which execute based on selected device.

Please suggest how i can achieve this. As my test cases gets failed even though same test pass in different device/browser.

**Comment by jan-molak** [comment]
Hi @WebTestNinja!

I'd suggest creating a business-specific task that encapsulates the intent you're after and then making that task responsible for delegating the execution to another device-specific task depending on the condition.

For example, let's say that I want to have a high-level, business-specific task to register an account:

```typescript
actor.attemptsTo(
  Register.as(`jan.molak@example.com`, `P@ssword1`)
);
```

This task could have various implementations, specific to a given interface. For example:
```typescript
const RegisterOnDesktop = (username: string, password: string) => Task.where(`#actor registers as ${username} on desktop`, 
    Enter.theValue(username).into(...),
    Enter.theValue(password).into(...),
    ...
);
const RegisterOnTablet = ...
const RegisterOnMobile = ...
```

With device-specific implementations in place, you can now move onto making a decision which one to use. In the below example I use an `env` variable, but you can use whatever you like:

```typescript
class Register implements Task {
    static as = (username: string, password: string) => new Register(username, password);

    constructor(private readonly username: string, private readonly password: string) {
    }

    performAs(actor: PerformsTasks): PromiseLike<void> {
        switch(process.env.DEVICE) {
             case 'tablet':  return actor.attemptsTo(RegisterOnTablet(this.username, this.password);
             case 'mobile':  return actor.attemptsTo(RegisterOnMobile(this.username, this.password);
             case 'desktop':
             default:        return actor.attemptsTo(RegisterOnDesktop(this.username, this.password);
        }
    }

    toString = () => `#actor registers as ${this.username}`
}
```

Let me know if that helps!
Jan

**Comment by WebTestNinja** [comment]
Wow.. Awesome. Thats really cool and i am sure this will help.
Thank you for your help.
