### ISSUE TITLE
attributes

### ISSUE THREAD

**Issue by AG0819** [jan-molak/serenity-js#128]
I see these attributes in wait.ts:
export declare class Is {
    static visible: () => SuccessCondition<Target>;
    static invisible: () => SuccessCondition<Target>;
    static present: () => SuccessCondition<Target>;
    static absent: () => SuccessCondition<Target>;
    static selected: () => SuccessCondition<Target>;
    static clickable: () => SuccessCondition<Target>;

Are there or can they be added to, disabled instead of clickable or rather than selected, not selected?

**Comment by jan-molak** [comment]
Sure, it's all composable so if you need a different condition you can write one yourself and plug it in. For example:

```typescript
const IsNotClickable = ()  => Is.aTargetThat(new IsNotClickable());

class IsNotClickable implements Condition<ElementFinder> {
    check = (thing: ElementFinder): Function => protractor.ExpectedConditions.not(protractor.ExpectedConditions.elementToBeClickable(thing));
    name  = () => 'clickable';
}

Wait.until(target, IsNotClickable());
```

Check out [the source code](https://github.com/jan-molak/serenity-js/blob/9a2274ece9403ccd26ede55fe4e4300d58ed26e3/packages/serenity-js/src/serenity-protractor/screenplay/interactions/wait.ts#L40) for more examples.

Let me know if that helps!
Jan

**Comment by AG0819** [comment]
That was helpful! All set, thank you!
