### ISSUE TITLE
Unable to download Serenity BDD CLI jar

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#135]
Hi everyone, I'm having an issue trying to download the BDD CLI Jar in a redhat machine behind a proxy.

I tried doing the following:

1. First I didn 't set the proxy and I got the following message: 

error: Looks like an error occurred downloading the Serenity BDD CLI jar. getaddrinfo ENOTFOUND dl.bintray.com dl.bintray.com:443
error: Looks like an error occurred downloading the Serenity BDD CLI jar. getaddrinfo ENOTFOUND dl.bintray.com dl.bintray.com:443

Looks like the dl.bintray.com dl.bintray.com:443 didn't exist.

Then I set the proxy configuration for the npm and the machine:

npm config set registry http://registry.npmjs.org/
npm config set proxy http://theproxy:myport
npm config set https-proxy http://theproxy:myport

and also:

export http_proxy=http://theproxy:myport
export https_proxy=https://theproxy:myport

And now I'm getting the following message:

error: Looks like an error occurred downloading the Serenity BDD CLI jar. tunneling socket could not be established, cause=socket hang up
An error occurred. Error: Looks like an error occurred downloading the Serenity BDD CLI jar. tunneling socket could not be established, cause=socket hang up
    at /home/mesaj/downloadbddclijar/node_modules/serenity-cli/lib/actions/logging.js:8:35

Also I tried this:

 wget https://dl.bintray.com/serenity/maven/net/serenity-bdd/serenity-cli/0.0.1-rc.1/serenity-cli-0.0.1-rc.1-all.jar

And I was able to download the jar file.

Any ideas how I can solve this?

Thanks!

**Comment by jan-molak** [comment]
Hi @jdmesalosada and sorry for being a bit slow to reply. Are you still facing this issue?

**Comment by jdmesalosada** [comment]
Sorry, Jan I already resolved this. This was happing due proxy issues.
Thanks.
