### ISSUE TITLE
is there a version that includes the fix for node 8.x ? 

### ISSUE THREAD

**Issue by CamiloCode** [jan-molak/serenity-js#136]
I saw that you made a change to serenity core 1.5.5 including that fix but I dont see any serenity-js version that includes it. Thanks!

**Comment by jan-molak** [comment]
Hey @CamiloCode! `serenity-js` depends on the [latest minor version](https://github.com/jan-molak/serenity-js/blob/master/packages/serenity-js/package.json#L40) of `@serenity-js/core` available. To get the latest version you can either re-install your `node_modules` or explicitly depend on `"@serenity-js/core": ">= 1.5.5"`.

Let me know if that helps?

Jan

**Comment by jan-molak** [comment]
`serenity-js` version `1.10.2` depends on the version of `@serenity-js/core` that [contains the fix](http://serenity-js.org/changelog.html#1102-2018-01-10).
