### ISSUE TITLE
Assertion for DOM not present in web page

### ISSUE THREAD

**Issue by WebTestNinja** [jan-molak/serenity-js#138]
Hi Jan,

i would like to assert cucumber scenario where error message is not displayed when i just switch focus on two blank input field on web page but Error message displayed when i enter some text in input field and then make it blank by deleting entered text.

The challenge here i am facing that when trying to assert error message DOM element not present on screen.

I am trying to do something like this 

```
static FB_UserName_Error = Target.the('FB username input').located(by.css('.form-container .error'));

EnsureThat(FlyingBlueUI.FB_UserName_Error).isNotVisible()

export const EnsureThat = (field: Target) => ({
   isNotVisible: () => Task.where(`#actor ensures that the ${field} is not visible`,
      See.if(WebElement.of(field), el => expect(el).to.eventually.be.not.present),
    ),
});
```

But i am getting error - NoSuchElementError: No element found using locator: `By(css selector, .form-container .error)`
because error message is not displayed by just focus on input field and hence .error class element is not present in web page. And when trying to locate element for assertion, it throw error.

Please suggest how can i assert when DOM element is not available on web page.

**Comment by jan-molak** [comment]
Hi there!

[Protractor docs](http://www.protractortest.org/#/api?view=ElementFinder.prototype.isPresent) suggest the following approach:

```
// Element exists.
expect(element(by.binding('person.name')).isPresent()).toBe(true);

// Element not present.
expect(element(by.binding('notPresent')).isPresent()).toBe(false);
```

Since `WebElement.of(field)` returns an `ElementFinder`, you should be able to do something along the lines of:

```typescript
See.if(WebElement.of(field), el => expect(el.isPresent()).to.eventually.be.false)
```

Let me know if that helps!
Jan

**Comment by WebTestNinja** [comment]
Thank you Jan for your help on this.
It works.

**Comment by jan-molak** [comment]
@tfarrar - sure, it's much easier with 2.0:

```typescript
import { Target } from '@serenity-js/protractor';
import { Ensure } from '@serenity-js/assertions';
import { by } from 'protractor';

const widget = Target.the('widget').located(by.css('.some-class'));

actorCalled('Eddie').attemptsTo(
    Ensure.that(widget, isPresent())
)
```

You can also compose expectations like [`isPresent`](https://serenity-js.org/modules/protractor/function/index.html#static-function-isPresent), for example:

```typescript
import { Target } from '@serenity-js/protractor';
import { Ensure, not } from '@serenity-js/assertions';
import { by } from 'protractor';

const widget = Target.the('widget').located(by.css('.some-class'));

actorCalled('Eddie').attemptsTo(
    Ensure.that(widget, not(isPresent()))
)
```

And you can use expectations with [`Wait`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/Wait.ts~Wait.html) too:

```typescript
import { Target, Wait } from '@serenity-js/protractor';
import { Ensure } from '@serenity-js/assertions';
import { by } from 'protractor';

const widget = Target.the('widget').located(by.css('.some-class'));

actorCalled('Eddie').attemptsTo(
    Wait.until(widget, isPresent())
)
```

Does this help?
