### ISSUE TITLE
Cucumber Data Tables do not appear in Serenity Report

### ISSUE THREAD

**Issue by joekeen** [jan-molak/serenity-js#14]
We use Cucumber Data Tables with out steps.

For example (from https://cucumber.io/docs/reference#data-tables):

```
Given the following users exist:
  | name   | email              | twitter         |
  | Aslak  | aslak@cucumber.io  | @aslak_hellesoy |
  | Julien | julien@cucumber.io | @jbpros         |
  | Matt   | matt@cucumber.io   | @mattwynne      |
```

The Data Table does not appear in the description of the step in the Serenity Report. 

Only: 

"Given the following users exist:"

**Comment by jan-molak** [comment]
Hi @joekeen and thanks for reporting this issue, it seems like a bug, let me look into this.

**Comment by nbarrett** [comment]
I will be curious to see how this is handled as I've never seen a data table in a serenity report before. Is this a limitation with which fields in the cucumber json are passed to the serenity reporter or that serenity itself doesn't do data tables?

**Comment by jan-molak** [comment]
@joekeen - please update `serenity-js` to the latest version, which supports both DataTable and DocString arguments of cucumber steps, as per the [release notes](https://github.com/jan-molak/serenity-js/releases/tag/v0.10.2).

@nbarrett - It's just a difference between how Cucumber reports regular step variables and the special "arguments", such as DataTables and DocStrings, which need to receive some special treatment. 

Many thanks for helping make Serenity/JS even better!
Jan

**Comment by joekeen** [comment]
Hi @jan-molak, I have updated and now the report includes the DataTable argument as required. Thanks for your work on Serenity/JS!

**Comment by jan-molak** [comment]
Lovely, thanks for letting me know, glad that you found it useful :-)
