### ISSUE TITLE
TypeError: Cannot read property 'theActorCalled' of undefined

### ISSUE THREAD

**Issue by vsadhana** [jan-molak/serenity-js#152]
I am building a mini project of my own to understand the Screenplay pattern.

The problem I am facing is that my `return this.stage.theActorCalled(name).attemptsTo` in my steps.ts file does not read the Actors.ts inspite of me importing it.
Also, it is not clear as to how to instal the "packages" folder similar to the one provided in this repo, as I have a feeling that 'theActorCalled' method from Stage class is not being called.
This is my error log:
![screen shot 2018-01-24 at 15 46 11](https://user-images.githubusercontent.com/34453113/35356225-caee50f2-011d-11e8-80ba-b20dec6381e8.png)

This is my file structure, as you may notice I don't have the "packages" folder as in the repo.
![screen shot 2018-01-24 at 15 48 07](https://user-images.githubusercontent.com/34453113/35356328-12778b3c-011e-11e8-9d03-d5ad3679c673.png)

This is my actor.ts file:
![screen shot 2018-01-24 at 15 49 08](https://user-images.githubusercontent.com/34453113/35356355-2a9ce388-011e-11e8-99f1-c83762f1ce89.png)

This is my step definition class:
![screen shot 2018-01-24 at 15 51 18](https://user-images.githubusercontent.com/34453113/35356473-7d4200d2-011e-11e8-895c-19a58b70330a.png)

And, this is my protractor config file:
![screen shot 2018-01-24 at 15 53 14](https://user-images.githubusercontent.com/34453113/35356542-bda549c2-011e-11e8-8121-69598c910fa9.png)

Thanks in advance!!

**Comment by jan-molak** [comment]
Hi @vsadhana! If you want to refer to stage using `this.stage` you'll need to set this variable up first.
With cucumber this is typically done using the `world.ts` file, like in [this example](https://github.com/jan-molak/serenity-js/blob/4b7d98290aefc98676fee04562b2a4d2f8d3fbed/examples/todomvc-protractor-cucumber/features/support/world.ts). This approach is useful if you have multiple step definition files and you want to share the stage across them.

If you have a simpler scenario with one step definition file you can instantiate the stage without the `world.ts`, like in [this example](https://github.com/serenity-js/seed-cucumber/blob/777a1512d724a6ff1801f752137b1c0a7035d5d4/features/step_definitions/steps.ts).

An even simpler scenario could be to not use the stage at all and instead just use the actor directly (this should be good enough for a simple experimental project):

```typescript
export = function steps() {

    const Betty = Actor.named('Betty').whoCan(BrowseTheWeb.using(protractor.browser));

    this.Given(/some regex/, function() {
        return Betty.attemptsTo(
        );
    });
};
```

Hope this helps!
Jan
