### ISSUE TITLE
Explicit wait in Serenity for non angular apps

### ISSUE THREAD

**Issue by Chirag-SSENSE** [jan-molak/serenity-js#158]
I noticed that it is hard to automate nonangular apps with a protractor. I am currently using these methods which I added it to current serenity click and enter functions to add the explicit wait. However, I would like to know if there is a thing I can add to the config file that will automatically wait for the dom to load before it starts to click any button or enter any text value? What is the good practice?

```
import { Enter, Click } from "serenity-js/lib/screenplay-protractor";
import { protractor, element } from "protractor";

var EC = protractor.ExpectedConditions;

export class Wait{
    constructor() {
    }

    enterValue(text:any, locator:any) {
        //Enter.theValue comes from serenity
        return browser.wait(EC.elementToBeClickable(element(locator)), 5000)

        .then(function(){
            return Enter.theValue(text).into(locator);
        });

    }

    clickOn(locator: any): any {
        //Click.on comes from serenity
        return browser.wait(EC.elementToBeClickable(element(locator)), 5000)

        .then(function(){
            return Click.on(locator);
        });
    }
};
```

When I try to use this function:

`WaitFor.enterValue('bruno@ssense.com', LoginPageMap.textLoginEmail),`

I get this error:

Argument of type 'Promise<Enter>' is not assignable to parameter of type 'Activity'.
  Property 'performAs' is missing in type 'Promise<Enter>'.

FYI LoginPageMap.textLoginEmail is defined as:
```

export class LoginPageMap {
  static textLoginEmail: Target = Target.the('"Email address" text field').located(by.css('.login [name="email"]'));
  static textLoginPassword: Target = Target.the('"Password" text field').located(by.css('.login [name="password"]'));
  static buttonLogin: Target = Target.the('"LOGIN" button').located(by.css('#submitLogin'));
}
```

@jan-molak

**Comment by nbarrett** [comment]
Hey @Chirag-SSENSE - I use the following approaches to wait for something in the UI to either be visible (something I want to interact with) or invisible (say a progress indicator) before commencing with the rest of the actual tasks I want to run:

`Wait.upTo(Duration.ofSeconds(<seconds>)).until(<target>, Is.visible()))`
or
`Wait.upTo(Duration.ofSeconds(<seconds>)).until(<target>, Is.invisible()))`

The following screenplay interactions are available within serenity-js:
- visible
- invisible
- static present
- static absent
- static selected
- static clickable

However, having said all that, it might be worth making sure that you have your ['global' timeouts set properly](http://serenity-js.org/overview/configuration.html#timeouts) as it might just be a case of needing to generally wait a bit longer than the default protractor settings.

**Comment by Chirag-SSENSE** [comment]
@nbarrett , how can we define the target? can you give an example? Is it for example - by.cass('locator') ?

**Comment by nbarrett** [comment]
@Chirag-SSENSE - your updated code still seems to be attempting to create your own Wait class, including referring directly to protractor.ExpectedConditions. The examples I showed you above demonstrate the built-in Serenity-js Wait API which I suspect will meet the your requirements. Behind the scenes, serenity-js wraps the the protractor API calls but provides a clean task-based api for you to use in your code. My recommendation would be to have a look at [the tutorial](https://github.com/serenity-js/tutorial-cross-app-testing) which includes examples for non-angular apps and other really handy examples for more advanced areas such as Questions. It might be easier to get those up and running first, then see how you can take those ideas into your own application?

**Comment by Chirag-SSENSE** [comment]
@nbarrett , I just realized it has to be used directly in the step definition. Thank you so much for your time. I will add it manually.

**Comment by jan-molak** [comment]
@Chirag-SSENSE did @nbarrett's suggestion help you solve the problem? If so, please let me know so we can close the ticket.

**Comment by Chirag-SSENSE** [comment]
Hi Jan,

Assuming that it can only be used in the step definition directly, yes I was able to resolve the issue. Thank you so much for your help :)

**Comment by jan-molak** [comment]
No worries, glad we could help :-)
