### ISSUE TITLE
Session not being restarted while testing multiple users on the same feature file

### ISSUE THREAD

**Issue by Chirag-SSENSE** [jan-molak/serenity-js#167]
I am trying to test few users using the feature file, this is what my feature file look like:

//example.feature
`Feature: Add item and place the order for that item
	In order to wear something new
	As an online shopping customer
	I want to be able to add an item to my shopping bag and then place the order

	Scenario Outline: Add an item to shopping bag to place the order using PaypalPro
		Given "<User>" is logged in to his "<EnvName>" account
		 When he searches item with SKU "<SKUID>" from "<Gender>" section and adds it to his shopping bag
		 Then "<User>" can place the order
	Examples:
		| User         | EnvName | SKUID        | Gender |
		| CanadaQCUser | SSENSE  | 51230M000010 | men    |
		| GBUser       | SSENSE  | 51230M000010 | women  |
		| FranceUser   | SSENSE  | 51230M000010 | kids   |`

When I run this feature file - after passing the first user "CanadaQCUser" the other users fail the test because when it opens the browser the user is already logged in. What can be done to add in the config file so it clears the cookies or cache so the when it tests the other users it is already not logged in.

**Comment by jan-molak** [comment]
Hey @Chirag-SSENSE if all your test scenarios require the user to log in, perhaps you could add an [after](https://github.com/cucumber/cucumber-js/blob/1.x/docs/support_files/hooks.md) hook that logs them out? This would ensure that every scenario leaves the system in a clean state, despite the outcome of the scenario (pass/fail).
