### ISSUE TITLE
Travis build for PRs is failing

### ISSUE THREAD

**Issue by InvictusMB** [jan-molak/serenity-js#17]
I don't know why is that happening. I suspected that I broke something with changing TS compile target for specs but it seems to fail irrespective of those changes. 
So I played around for a while and created 3 separate PRs touching different areas but builds for all of them fail.
I bet the build would fail even if I change only the readme.

**Comment by jan-molak** [comment]
That's weird; it seems to be complaining about the browser crashing. Maybe something to do with Browserstack permissions/setup for the PRs? Let me check that.
