### ISSUE TITLE
SerenityBDDReporter bug with some mocha hooks

### ISSUE THREAD

**Issue by ctaepper** [jan-molak/serenity-js#171]
the reporter cannot handle tasks in `afterEach`:
```
[15:46:15] E/launcher - Cannot read property 'append' of undefined
[15:46:15] E/launcher - TypeError: Cannot read property 'append' of undefined
    at /Users/ct/Projekte/xxx/packages/e2e-tests/node_modules/@serenity-js/core/src/reporting/rehearsal_report.ts:31:27
```
the same error occurs, when trying to define a `before`

I think the reporter doesn't know to which scene to append the activity to, with `before` it has not startet yet, with `afterEach` the scene already has concluded

edit: the afterEach Bug only appears if there are at least 2 `it`s in the `describe`

**Comment by jan-molak** [comment]
Hi @ctaepper, yes, you're right. @Tom-Hudson's ticket #104 has a bit more detail so let's track it there if that's OK? I finally have some time to work on the reporters so am hoping to get quite a few of those related tickets done.
