### ISSUE TITLE
SerenityJS 1.10.6 compatibility with Cucumber 4.0.0 

### ISSUE THREAD

**Issue by KhalidAriche** [jan-molak/serenity-js#176]
Hi
I posted an error on stackoverflow, for intergration SerenityJS 1.10.6 with Cucumber 4.0.0 [here](https://stackoverflow.com/questions/48987045/serenityjs-integration-with-protractor-and-cucumber-doesnt-work)

**Comment by jan-molak** [comment]
Hi there! At the moment Serenity/JS supports Cucumber 1.3, I'm planning to add support for Cucumber 4.0 soon, but please use 1.3 for the time being. Support for Cucumber 2 and above is tracked under #28.
