### ISSUE TITLE
Checking if the element is present then perform actions

### ISSUE THREAD

**Issue by Chirag-SSENSE** [jan-molak/serenity-js#185]
I am trying to check if the element is present. If yes, I would like to perform some actions. I.e

```
ProductDetailPageMap.addToWishlist.isPresent().then(function (result) {
            if (result) {
                Click.on(ProductDetailPageMap.addToWishlist)
            } else {
                Click.on(ProductDetailPageMap.addToWishlist)
                Click.on(ProductDetailPageMap.addToWishlist)
```
However, I do not think I can do this in serenity? Note that ProductDetailPageMap.addToWishlist is defined as:

`static addToWishlist		: Target = Target.the('"Add to Wishlist" button').located(by.xpath("//button[@type='submit']/span[.='Add to wishlist']"));`

**Comment by nbarrett** [comment]
Hi @Chirag-SSENSE - there is a PR #159 pending that would allow the following approach to be taken:

```
    performAs(actor: PerformsTasks): PromiseLike<void> {
        actor.attemptsTo(
            Check.whetherPromiseTrue(Presence.of(ProductDetailPageMap.addToWishlist))
                .andIfSo(
                    Click.on(ProductDetailPageMap.addToWishlist))
                .otherwise(
                    Click.on(ProductDetailPageMap.addToWishlist),
                    Click.on(ProductDetailPageMap.addToWishlist)));
    };

``` 

This would also require the addition of a Question as follows:

```
export class Presence implements Question<PromiseLike<boolean>> {

    public static of(target: Target): Presence {
        return new Presence(target);
    }

    answeredBy(actor: UsesAbilities): PromiseLike<boolean> {
        return BrowseTheWeb.as(actor).locate(this.target).isPresent();
    }

    constructor(private target: Target) {
    }
}

```

While I am waiting for the PR to be merged (hopefully!), I use the [ConditionalPerformable](https://github.com/jan-molak/serenity-js/pull/159) performable extensively in my own specs and it's really opened up the available options. Hope this helps!

**Comment by Chirag-SSENSE** [comment]
@nbarrett , how do i import Check?

This is my task.ts page

<img width="853" alt="screen shot 2018-03-09 at 10 42 25 am" src="https://user-images.githubusercontent.com/35231678/37215666-a80d9e4a-2386-11e8-9c10-2653daa2dc77.png">

and this is my question page:

<img width="852" alt="screen shot 2018-03-09 at 10 43 22 am" src="https://user-images.githubusercontent.com/35231678/37215699-bb456e98-2386-11e8-9af8-7593dee5adda.png">

**Comment by nbarrett** [comment]
Hi @Chirag-SSENSE - I mentioned above that I'm still waiting for feeback/merge from @jan-molak on PR #159. A suggestion while we are waiting for this would be for you would be to copy [the source](https://github.com/jan-molak/serenity-js/pull/159/files#diff-b0a3ea8b789f25948067cc3f2db294ecR1) into your own project and see whether you get the desired outcome?

**Comment by Chirag-SSENSE** [comment]
@nbarrett , is there anything else i can use except this?

**Comment by nbarrett** [comment]
only my suggestion above...

**Comment by jan-molak** [comment]
Hey @Chirag-SSENSE! The `Check` task is now available in `@serenity-js/core`, please update the module and [consult the unit tests](https://github.com/jan-molak/serenity-js/blob/23110f7cfce612151b1b65d399fc407d211ba5b1/packages/core/spec/tasks/check.spec.ts) for examples.

Best,
Jan
