### ISSUE TITLE
Validate visibility of elements inside a row table - Chained locators 

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#187]
Hi everyone,
I have the following due regarding how to find an element starting from another element and then make assertions in those elements. For example something like this in protractor:

element(by.css('some-css')).all(by.tagName('tag-within-css'));
or 
element(by.css('some-css')).element(by.tagName('tag-within-css'));

So I have a table. Let say the table container is div.table-container, the rows are identified by the class: div.row-identifier.
Inside each row I have several elements that I want to know if they are displayed. So I have to get all the row elements, and then search inside that element the others elements.

 My seudo looks like:

```
const table-container = "table-container";
const row-container = "row-container";

const element1InsideRow = "element1InsideRow";
const element2InsideRow = "element2InsideRow";

var allRowsElements =  table-container.find(row-container);//here I search the rows starting the table.

foreach(rowElement in allRowsElements){
Assert.IsDisplayed(rowElement.find(element1InsideRow )); //Now I search the element 1 starting the row
Assert.IsDisplayed(rowElement.find(element2InsideRow));

}

```

Thanks in advanced.

**Comment by jan-molak** [comment]
Hey @jdmesalosada! Support for nested targets has been proposed under #143 and that could be helpful, but I'd suggest looking into the [Journey Planner example](https://github.com/serenity-js/tutorial-journey-planner/blob/55de867a33f55662bde78b0f0930aa0208b0d51f/src/journey_planner/journeys_found.ts). I've created [a custom question](https://github.com/serenity-js/tutorial-journey-planner/blob/55de867a33f55662bde78b0f0930aa0208b0d51f/src/journey_planner/journeys_found.ts#L12) there which maps a table row to something a bit more meaningful - a `JourneySummary`.
With that model in place, I wrote [a custom assertion](https://github.com/serenity-js/tutorial-journey-planner/blob/55de867a33f55662bde78b0f0930aa0208b0d51f/src/journey_planner/journeys_found.ts#L32), which you can find being used [here](https://github.com/serenity-js/tutorial-journey-planner/blob/55de867a33f55662bde78b0f0930aa0208b0d51f/features/step_definitions/journey_planner.steps.ts#L52).

Does that help?

Jan
