### ISSUE TITLE
SerenityJS on Docker

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#191]
Hello all! I'm trying to create a docker image version on Serenity/JS, any tips of what should I use or do in order for Serenity/JS to run successfully on docker? Thanks! ^_^V

**Comment by jan-molak** [comment]
Hey @marktigno! What's your setup like and what are you hoping to accomplish? Would you like to have serenity tests deployed to a docker container together with your system under test, or run them locally via docker?

**Comment by marktigno** [comment]
hello @jan-molak! Thanks for the reply, i like to do both for some reasons:
Scenario 1 -  will be included running on our deployment pipeline and artifact the report generated from there. And Scenario 2 - running them on my local machine to checking newly committed scripts and do maintenance. I have created a Dockerfile that I'm testing on my local machine (CentOS 7 image with NodeJS 8) but Chrome crashes abnormally when I run it.

**Comment by marktigno** [comment]
Hello @jan-molak, I was able to build a Docker image running Serenity/JS on it. I did some trial and error on it and now I successfully run on Docker (yehey!). I'm closing this ticket for now. And if someone likes to ask how I made it then I can share the steps on how to do it on Docker. Thanks! ^_^V

**Comment by jdmesalosada** [comment]
Hi @marktigno I'm interested on that, could you share the image on docker hub?
Thanks.

**Comment by marktigno** [comment]
Hello @jdmesalosada, sure I'll try to upload the image on docker hub. I have to create a documentation steps on how to do it.

**Comment by jdmesalosada** [comment]
Awesome!

**Comment by kdp88** [comment]
very interested in this as well

**Comment by jan-molak** [comment]
@marktigno - that sounds great! Let me know if you'd like to publish your docs on serenity-js.org, or link to them :-)

**Comment by marktigno** [comment]
Hello! Sorry for the delay on this one (went on holiday recently ^_^V). I'm currently creating a docker repo now to enable you all start running your tests on docker. I'll publish the Dockerfile there and steps on how to run it. Thanks! :)

**Comment by marktigno** [comment]
Hi guys! I've created a repo here to upload the docker file: [https://github.com/marktigno/serenityjs-docker](url)
This is still a working progress but I'll let you all know once done on this. Thanks!

**Comment by marktigno** [comment]
Hello all! I'm done testing the docker build for the serenityjs-docker version. I've already pushed the a git repo of a running version of serenityjs on the link I've posted before. Next to do is to push the Dockerfile on "https://hub.docker.com/r/marktigno/serenity-js/". Will update on it once done. Thanks! ^_^V

![image](https://user-images.githubusercontent.com/13494822/39124785-4c6ea90e-472f-11e8-951c-d0ea9b4a5950.png)

**Comment by marktigno** [comment]
Hello @jan-molak,

Looks like I stumble upon on a problem when I checked the screenshots of the report. It seems the font used on the TodoMVC app is not recognized by the browser or CentOS itself. I have the screenshot attached on this comment. Mind to check on this one? Thanks! :)

![image](https://user-images.githubusercontent.com/13494822/39125182-b66ef54c-4730-11e8-91ec-89299810a011.png)

**Comment by marktigno** [comment]
Hello all! You may start pulling it from docker: https://hub.docker.com/r/marktigno/serenityjs-docker/

Thanks! ^_^V

**Comment by paolocarrasco** [comment]
Another image for running Serenity within GitlabCI (maybe other CI servers too) can be found here:

https://hub.docker.com/r/paolocarrasco/serenity-js-for-gitlab-ci

It can be used by putting this in the .gitlab-ci.yml:

```yml
image: docker.io/paolocarrasco/serenity-js-for-gitlab-ci:<version>

cache:
  paths:
    - node_modules/


stages:
  - build
  - test


build:
  stage: build
  script:
    - npm install

execute-examples:
  stage: test
  script:
    - npm test```

**Comment by jan-molak** [comment]
Hello @marktigno, @jdmesalosada, @kdp88, @paolocarrasco and @nbarrett! It's a bit embarassing how long it's been since our last conversation about Docker containers for Serenity/JS. I hope you'll still welcome the news that Serenity/JS now offers an official Docker image capable of running both Playwright and WebdriverIO tests.

I'd love to hear what you think! https://serenity-js.org/handbook/integration/docker/
