### ISSUE TITLE
SerenityJS and Is.condition (ex. Is.clickable) timeout

### ISSUE THREAD

**Issue by san-ouadghiri** [jan-molak/serenity-js#195]
Hi Jan,

Sometime knowing what timeout using SerenityJS can be challenging. Is it mocha, is it protractor, is it selenium, is it within serenity's code itself -> I think it may be good documentation material to sum-up what can be customized where, when it comes to timeout.

This said here is my question.
I need to be able to wait for a button to be clickable more than 5000ms. How can I custom the timeout in a expression such as _Wait.until(Account.logout, Is.clickable())_ ?

```
Wait.until(myButton, Is.clickable()),
Click.on(myButton),
```

I found out within protractor > built > expectedCondition.js 

```
@example
 * var EC = protractor.ExpectedConditions;
 * var button = $('#xyz');
 * var isClickable = EC.elementToBeClickable(button);
 *
 * browser.get(URL);
 * browser.wait(isClickable, 5000); //wait for an element to become clickable
 * button.click();
```

Could you advise me on a way to express that wait within my scenario, but with a different timeout?
And is there a way, not to change the timeout wait by wait but globally (for every wait.until I use for ex.)?

**Comment by san-ouadghiri** [comment]
I should add that my error is:
TimeoutError: The "myButton" button did not become clickable within 5000ms
[e2e] Wait timed out after 7831ms

In case mocha was not the right culprit :).

**Comment by san-ouadghiri** [comment]
So thanks to an example of yours ([this one](https://github.com/jan-molak/serenity-js/blob/660f618a647eca71beff30e290c59b6471deb19c/spec/cookbook/waiting.recipe.ts)) I realized, I could probably use Wait.upTo(...).until(...). And it looks like it does what I wanted. So I guess this issue can be closed.

Sorry for this long post and thanks again for all your work !

San.

**Comment by jan-molak** [comment]
I'm glad that you managed to sort it out! Although to be fair, this area deserves some better documentation so I'll look into that.
