### ISSUE TITLE
latest protractor and selenium

### ISSUE THREAD

**Issue by tremkonzah** [jan-molak/serenity-js#2]
how to update serenity-js to use latest version of protractor (4.0.10) and selenium (3.0.1)?

**Comment by jan-molak** [comment]
Hey @tremkonzah and thanks for giving Serenity/JS a try! 😄 

I've updated the dependency on Protractor to 4.0.10 and made it a `peerDependency`. This way you can update Protractor independently of Serenity/JS. Those changes are live as of `0.6.1`, which is now [available on npm](https://www.npmjs.com/package/serenity-js).

In terms of Selenium 3.0.1 - I don't think Protractor [supports it yet](https://github.com/angular/protractor/blob/9e07de09be640efed90f539cd136a9dcfbb4d8fc/package.json#L27), and both Serenity/JS and Protractor need to be in sync here I'm afraid.
Also, there are still issues with the stability of Selenium 3.0.1, which @wakaleo [summarised here](https://github.com/serenity-bdd/serenity-core/issues/447#issuecomment-258074393). Those issues will affect the speed at which libraries like Serenity/JS or Protractor can adopt it.

**Comment by tremkonzah** [comment]
@jan-molak many thanks
