### ISSUE TITLE
REST API: Pass URL as an argument instead of setting it as a property value

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#209]
Hello all! I'm creating a REST API tests using serenityjs/rest package and I'm following examples posted here but I want to know how to pass the URL as a CLI argument rather than setting it as a property value on a config file or any .ts file?

**Comment by jan-molak** [comment]
Hey @marktigno! Do you mean as an argument set at runtime? You could use an env variable for example:

`API_URL=https://mycompany.com/api npm test`

and then

```typescript
Actor.named('Adam').whoCan(CallAnApi.at(process.env.API_URL))
```

Does that help?
Jan

**Comment by san-ouadghiri** [comment]
Well, Jan would know better, but I think that UI or API actually doesn't change the matter. It's more about how to give the info to protractor (acting as your test runner), and then how it can send that data to your tests, shall they be API or UI.

Ex. (using an ability, there's other way to do that)
```
UI : return Actor.named(firstNameActor).whoCan(Open.browserOn(HOME_PAGE));
API : return Actor.named(firstNameActor).whoCan(CallAnApi.at(API_ENDPOINT));
```

With for example
```
export const API_ENDPOINT = ENV === 'prod' ? `https://api.mysite.com` : `https://api.mysite-${ENV}.com`;
export const HOME_PAGE = ENV === 'prod' ? `https://www.mysite.com` : `https://www.mysite-${ENV}.com`;
```

And then using something like https://moduscreate.com/blog/protractor_parameters_adding_flexibility_automation_tests/ article describe, maybe calling 

> protractor conf.js --parameters.env=preprod

**Comment by marktigno** [comment]
Thanks @san-ouadghiri and @jan-molak for the comments, I will try these on my tests here. Closing this ticket for now. :)
