### ISSUE TITLE
Uploading a file via chrome alert

### ISSUE THREAD

**Issue by emosGambler** [jan-molak/serenity-js#228]
Hi all,

We have a test case, where file a should be uploaded to server. Currently we have a button that opens a chrome alert and there user is suppose to choose a file.

How can I upload a file in UI like this?

Thanks.

**Comment by emosGambler** [comment]
Ok, I have managed to upload a file by entering path to the input directly. Can be closed!

**Comment by jan-molak** [comment]
Excellent, I'm glad you managed to sort it out! :-)

Thanks for letting me know 👍 
Jan
