### ISSUE TITLE
"$()" from protractor is not considered a valid locator

### ISSUE THREAD

**Issue by emosGambler** [jan-molak/serenity-js#231]
When I'm trying to find an element using `by.css` method like this:

`import { by } from 'protractor`
`static someElement = Target.the('Some Element').located(by.css('css.selector'));`

The element is successfully found. but when I try to use `$()`, which should be the same as `by.css` like this:

`import { $ } from 'protractor`
`static someElement = Target.the('Some Element').located($('css.selector'));`

the console says:
[protractor] Message:
[protractor] TypeError: Invalid Locator

And I think it should be possible to use. Am I thinking correctly?

**Comment by jan-molak** [comment]
Hi @emosGambler!

Unlike `by.css(...)`, which represents a `locator`, the [`$` function](https://github.com/angular/protractor/blob/3702a709fe251fed1de9ee1eab38593c2c371e94/lib/element.ts#L1069) is actually equivalent to saying:
```javascript
element(By.css(selector))
```
So it also resolves the element identified by the selector.

Does that help?
Jan

**Comment by emosGambler** [comment]
Hi Jan,

Yes, you are right!

Thanks,
Jacek
