### ISSUE TITLE
Press Enter key on Button

### ISSUE THREAD

**Issue by jmkamran** [jan-molak/serenity-js#238]
![capture](https://user-images.githubusercontent.com/31004762/41801012-966e01bc-7691-11e8-92e8-43f3ea17b748.PNG)
When I enter id in textbox, I click on search button by mouse but I want to press enter key to click on search button. How can I do? Kindly help.

        }
       protected visitid =0;
        protected cvideo;
        protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();
            ////var  visitID = 0;
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "apply-changes-button"), 1);
            
            var services = this.getService();
			buttons.push({
				title: Q.text('Search'),

				cssClass: 'edit-permissions-button',
				icon: 'fa-search text-green',
				
                onClick: (e) => {
                    //new VisitDialog({
                    //    entityId: this.entity.CNIC_Passport
                    //});
				
					var request = this.getSaveEntity();
					
                    Q.serviceCall({
                         url: Q.resolveUrl('~/Services/' + this.getService() +'/FillData'),
                        request: request
                        ,
						onSuccess: response => {
							
                            this.form.InivitationId.value = response["InivitationId"];
                            this.form.EndDate.value = response["EndDate"];
                            this.form.StartDate.value = response["StartDate"];
                            this.form.HostId.value = response["HostId"];
                            this.form.VisitorId.value = response["VisitorId"];
                           // this.form.VisitorPicture.value.Filename = new Serenity.UploadedFile();
                            //this.form.VisitorPicture.value.Filename = response["VisitorPicture"];
                             
                            this.form.Description.value = response["Description"];
                            this.form.CompanyID.value = response["CompanyID"];

**Comment by jan-molak** [comment]
Hi there! I think you might be asking the question about the [Serenity application platform](https://github.com/volkanceylan/Serenity) rather than Serenity/JS - the acceptance testing library?

Unless you're trying to test a Serenity application with a Serenity/JS test?

Jan

**Comment by jmkamran** [comment]
I add button  but I want to press enter to click button. Hope will understand. I am using serenity application platform.

**Comment by jan-molak** [comment]
I see. It looks like the issue is related to the Serenity Application Platform rather than this project?
Please feel free to re-open this ticket if what you're doing is writing an automated test using Serenity/JS.

Also, it looks like your question [has already been answered there](https://github.com/volkanceylan/Serenity/issues/2444#issuecomment-312580182).
