### ISSUE TITLE
Unable to Fetch a text and store it into a string

### ISSUE THREAD

**Issue by srinivasbudh** [jan-molak/serenity-js#24]
@jan-molak ,

During my test I want to save the text of a web element and need to assert later during the test.

I'm sure "chai.expect" will help me in asserting, However I couldn't find any interaction to save the text of the Web element during the Test into a string. Do we have any such Interaction already Implemented??

Example:

`WebElement txtBoxContent = driver.findElement(By.id(WebelementID));
String testValue=txtBoxContent.getText();`

Above is the way to do it in Selenium, not sure how to do it here. I have tried Text.of However its returning me an object and when I try to assign it to Sting its throwing me error "**argument type question string is not assignable to parameter type perform-able**". 

`confirmationVoucher = Text.of(confirmationPage.VoucherCode)` 

I'm new to JavaScript/Typescript, Any help on how to handle the above scenario will be a great help. Kindly let me know if this issue is in-appropriate here I can close this issue.

**Comment by jan-molak** [comment]
Hello @srinivasbudh!

Yes, `Text.of(confirmationPage.VoucherCode)` would return a [`Question`](http://serenity-js.org/scenarios/screenplay-pattern.html#question), which needs to be evaluated in the context of your actor before it can be asserted on.

```typescript
// To create a Question:
Text.of(confirmationPage.VoucherCode);

// To evaluate a Question and return a Promise:
actor.toSee(confirmationPage.VoucherCode);

// To assert on the value of the returned Promise:
expect(actor.toSee(confirmationPage.VoucherCode)).eventually.equal('expected code')
```

Does that help?

**Comment by srinivasbudh** [comment]
Hi ,

Sorry if I have conveyed it wrongly. My question was to know if there is any interaction to take the text of a web element and store it into a string. Is this possible?? Like in selenium getText() which will help to store the value into a string as mentioned above in issue

**Comment by jan-molak** [comment]
Sure, although it would be easier for me to suggest something if I understood your test scenario a bit better. I'm guessing it perhaps goes somewhat along the lines of:
- an actor starts working with the application
- they're shown some sort of a voucher code
- they perform some additional tasks (add items to a basket perhaps, go to checkout?)
- they need to enter the voucher code they've been shown before, maybe before they pay for the items?

Is that what you're trying to accomplish?

**Comment by srinivasbudh** [comment]
Yes, Jan functionally I'm looking at the same thing  with a small change

1. an actor starts working with the application
2. they're shown some sort of a voucher code specific to this user as special offer
3. they perform some additional tasks (add items to a basket perhaps, go to checkout?)
4. Proceeds to payment page where  he see multiple voucher code with different offers but he need to check if the specific voucher offered to him during step 2 is there in the list of vouchers
And then select it

**Comment by jan-molak** [comment]
I see, thanks for the explanation.

This functionality was not available out of the box at the time when you asked the question.
However, since it seems to be a common scenario, it's now built-in 😄 

Your scenario is now supported via the ability to `TakeNotes`, please check:
- the [unit tests](https://github.com/jan-molak/serenity-js/blob/master/spec/api/screenplay/abilities/take_notes.spec.ts) for the API examples
- the brand new [documentation](http://serenity-js.org/design/assertions.html#delayed-assertions)

Hope this helps,
Jan

**Comment by lobmails** [comment]
@jan-molak : Thanks for providing the explanation above regarding getting the text out of an element.

However, when I'm trying to get text out of a select object (drop-down)I am facing issues.

Here is my code for your reference:

```
const stage = serenity.callToStageFor({
                            actor: name => Actor.named(name).whoCan(
                                                              BrowseTheWeb.using(protractor.browser),
                                                              TakeNotes.usingAnEmptyNotepad(),
                                                      ),
                       });

```
this.When(/Cucumber When Block/, function() {
        Actor.named('User').attemptsTo(TakeNote.of(RaceMeetings.SelectMeeting));
        return stage.theActorInTheSpotlight().attemptsTo(Click.on(RaceMeetings.Continue));
 });

I am new to SerenityJS, would you be able to provide an example to get text out of an element.

The unit tests link above seems to be broken.
I've implemented the code based on new documentation example, however, it's not helping.

**Comment by nizar-nizar** [comment]
this.Then(/^check something$/,function(){
var elemtext: PromiseLike<string> = james.toSee(Text.of(elem));
return elemtext.then(function(val)){
console.log(val);

})

**Comment by sudhir-kunchakuri** [comment]
I want to fetch the text from an xpath and store it in a string.

After entering all inputs and submitting , a new code will get generated and which looks like Customercode: IN02732114(number will dynamic).

Now i want to fetch this code and store it in a string and later want to use this string to search the data with this code.

i have used below snippet to get the text.

  public static Question<String> customer_code_value3() {
        return actor ->  Text.of(CustomerCreatePage.CUSTOMER_CODE_TEXT).viewedBy(actor).asString().substring(15, 26);
        }

now how can i store this in a string.

plz let me know 

@jan-molak

**Comment by jan-molak** [comment]
Serenity/JS v. 2 introduced a way to [`.map`](https://serenity-js.org/modules/core/class/src/screenplay/Question.ts~Question.html#instance-method-map) Questions using a [mapping function](https://serenity-js.org/modules/core/identifiers.html#screenplay-questions-mappings-string).

```typescript
Text.of(CustomerCreatePage.CUSTOMER_CODE_TEXT).map(actor => value => value.substring(15, 26)
```

**Comment by sudhir-kunchakuri** [comment]
![image](https://user-images.githubusercontent.com/70365103/105456436-2aabd780-5cab-11eb-9ad9-ab0d34d30add.png)

i have wrote like this 
  public static Question<String> customer_code_value3() {
        return Text.of(CustomerCreatePage.CUSTOMER_CODE_TEXT).map(actor => value => value.substring(15, 26));
        }

 and now i am getting errors like this 

 cannot resolve method 'map' in 'UIStateReaderBuilder'
Cannot resolve symbol 'actor'
Cannot resolve symbol 'value'

can u plz help me .. 
@jan-molak

**Comment by jan-molak** [comment]
@sudhir-kunchakuri [`UIStateReaderBuilder`](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/UIStateReaderBuilder.java) is part o Serenity BDD for Java, not Serenity/JS. If you're using the Java version you might want to raise this ticket [here](https://github.com/serenity-bdd/serenity-core/issues).
