### ISSUE TITLE
'Features' tab only generated when 'features' folder at root level.

### ISSUE THREAD

**Issue by maheshbenur** [jan-molak/serenity-js#241]
![features tab issue](https://user-images.githubusercontent.com/40716147/42125422-41a758e6-7c94-11e8-89d6-dd28f3383a39.png)

If I keep "features" folder under some hierarchy , "com/../../features" then 'Features' tab does not appear in report.

Is there any restriction with respect to a location of features folder in project?.

**Comment by maheshbenur** [comment]
- This issue resolved by mentioning feature folder path using parameter --features

serenity run --source target/site/serenity/ --destination test_reports/ **--features com/.../.../features**

**Comment by jan-molak** [comment]
I'm glad you manage to solve it, thanks for letting me know!
