### ISSUE TITLE
ERROR: expected '' to include 'Operation Success'. Why assertion in See.if return empty string sometimes?

### ISSUE THREAD

**Issue by jayaseelan-dev** [jan-molak/serenity-js#243]
I am facing an issue with See.if() - it returns empty string sometimes.

Tech stack used:

Serenity/JS with cucumber and protractor
P-Growl - Primeng growl component
Chai as promised - expect method
Here is the error: Assertion error: expected '' to include 'Operation success'

**steps.ts**

```
this.Then(/^he should see the user (.*) success message$/, (severity) => {

    browser.waitForAngularEnabled(false); // Workaround fix for p-growl

    return stage.theActorInTheSpotlight().attemptsTo(
        Messages.called(severity)
    );
});
```

**Task.ts**

```
import { PerformsTasks, Task, Enter, Click, See, Is, Wait, Text } from 'serenity-js/protractor';

import { expect } from '../utils/expect';
import { ListUI } from '../components/ui';

export class Messages implements Task {

  constructor(private severity: string) { }

  static called(severity: string) {
    return new Messages(severity);
  }

  performAs(actor: PerformsTasks): PromiseLike<void> {
    if (this.severity.toLowerCase() === 'success') {
        return actor.attemptsTo(
            Wait.until(ListUI.message, Is.present()),
            See.if(
                Text.of(ListUI.message),
                actual => expect(actual).to.eventually.include('Operation Success')
            ),
            Click.on(ListUI.messageCloseWidget)
        );
    }
  }
}
```

**ui.ts**

```
import { Target, Text } from 'serenity-js/protractor';
import { by } from 'protractor';

export class ListUI {

  static message = Target.the('Message Widget')
    .located(by.id('messages'));

  static messageCloseWidget = Target.the('Message Close Widget')
    .located(by.css('#messages .ui-growl-icon-close'));
}
```

Please help me. Thanks in advance.

**Comment by jan-molak** [comment]
Hi @jayaseelan-dev!

The first thing I noticed is that there might be a problem with the task:

```typescript
export class Messages implements Task {
  // ...

  performAs(actor: PerformsTasks): PromiseLike<void> {
    if (this.severity.toLowerCase() === 'success') {
        return actor.attemptsTo(
          // ...
        );
    }

   //  💣if the severity !== 'success' this method returns void, which will break the actor flow
   // consider adding a no-op:
   else actor.attemptsTo();
  }
}
```

Other than that the code seems fine. One thing that's probably worth checking is if the `ListUI.message` is populated dynamically in your application? If that's the case, even though you `Wait.until(ListUI.message, Is.present())`, it might be that the html element itself is present, but the text is populated asynchronously, so the test is synchronised correctly, but the assertion is performed before the message is rendered? It's hard to tell without seeing your app.

Does that help?
Jan

**Comment by jayaseelan-dev** [comment]
Thanks you for support.

I resolved the issue by providing **primeng growl message selector**.
Provided exact selector for message **(#messages .ui-growl-message).**

Below code fixed:

import { Target, Text } from 'serenity-js/protractor';
import { by } from 'protractor';

```
export class ListUI {

  static message = Target.the('Message Widget')
    .located(by.css('#messages .ui-growl-message'));

  static messageCloseWidget = Target.the('Message Close Widget')
    .located(by.css('#messages .ui-growl-icon-close'));
}
```

**Comment by jan-molak** [comment]
Excellent, I'm glad you managed to sort it out! Thanks for letting me know 👍
