### ISSUE TITLE
@manual tag does not ignore the scenario, it runs it anyway

### ISSUE THREAD

**Issue by emosGambler** [jan-molak/serenity-js#244]
So I am not sure, but I think when we put @manual tag above some scenario, it should completely ignore the test from execution, right? Apparently serenity launches the scenario anyway and then in the report there are statuses like "Passing (manual)" or "Failing (manual)" depending on the result of automated run, which is very odd to me.

![https://i.imgur.com/BteTI2F.png](https://i.imgur.com/BteTI2F.png)
![https://i.imgur.com/ntrEihA.png](https://i.imgur.com/ntrEihA.png)

**Comment by jan-molak** [comment]
Hi @emosGambler! It's actually Cucumber (rather than Serenity/JS) that executes the scenario, so in order to avoid running the `@manual` scenarios you'd need to tell Cucumber to ignore them:

```
// protractor.conf.js
    cucumberOpts: {
        require:    [ 'features/**/*.ts' ],
        format:     'pretty',
        compiler:   'ts:ts-node/register',
        tags:       ['~@manual']           // that's the important bit
    },
```

Hope that helps!

Jan

**Comment by SaikatDEV** [comment]
In this case, Serenity report won't have the live documentation of them. I would expect to have those scenarios in the report but not executed.

**Comment by wakaleo** [comment]
If the scenario is manual, why does it have step definitions? Manual scenarios are not intended to be automated, otherwise they wouldn’t be manual.
