### ISSUE TITLE
Github Page Link Broken

### ISSUE THREAD

**Issue by TechGuyTy** [jan-molak/serenity-js#25]
http://serenity-js.org

This link is broken

![2017-02-10_17-39-34](https://cloud.githubusercontent.com/assets/19700939/22846905/f780c640-efb7-11e6-93d1-abd72f8b09c3.png)

**Comment by jan-molak** [comment]
Thanks @TechGuyTy, it was a glitch in building the gitbook. It's fixed now and the website is up, looking forward to hearing your thoughts on Serenity/JS!

Hope you like it! :-)
Jan

**Comment by TechGuyTy** [comment]
Excited to check it out! quick turn around on the issue too. 

Thanks

**Comment by jan-molak** [comment]
No problem, have fun!

J
