### ISSUE TITLE
Hooks in serenity JS

### ISSUE THREAD

**Issue by AbhineetSharmax** [jan-molak/serenity-js#252]
Hi @jan-molak,

Wondering, do we have hooks in serenity-JS ? Can we have beforeEach()/afterEach() clauses in Serenity JS !!

I do have a function called as initialize() that needs to be called Just after the browser gets open and before Actor performs anything(ie. before step definition), for each Test. Your suggestion would help!! Thanks.

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax!

If you're using Serenity/JS with Cucumber it is Cucumber's responsibility to handle the hooks.
You can learn more about them from [Cucumber docs](https://github.com/cucumber/cucumber-js/blob/1.x/docs/support_files/hooks.md).

Basically, you'd need to create a file, such as `initialise.ts` under `features/support` with the following contents:

```typescript
export = function() {

    this.Before(function() {
        initialize();
    });
};
```

Please bear in mind that if the `initialize` function is asynchronous you need to "tell" Cucumber when you're done initialising so either return a `Promise`:

```typescript
export = function() {

    this.Before(function() {
        return initialize();
    });
};
```

Or call the callback:

```typescript
export = function() {

    this.Before(function(callback) {
        initialize(callback);
    });
};
```

Does this help?

Jan

**Comment by AbhineetSharmax** [comment]
Hi @jan-molak, 

So, Before/After clauses works only when the Scenario gets start/complete. Like this flow..

Before

  Scenario
         Example 1
         Example 2
   
After

Before/After would not handle each example.

Is there something like beforeEach afterEach in serenity? Which handle each examples too?

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax,

`Before/After` hooks are executed before and after each scenario, respectively. See [cucumber specs](https://github.com/cucumber/cucumber-js/blob/509e64fd5d9835c9101b33a642e6ccac459025b8/features/hooks.feature)

`BeforeAll/AfterAll` are executed before and after the entire test run, respectively. See [cucumber specs](https://github.com/cucumber/cucumber-js/blob/509e64fd5d9835c9101b33a642e6ccac459025b8/features/before_after_all_hooks.feature)

Hope this helps!

Jan

**Comment by igTkachov** [comment]
@jan-molak but as I see cucumber version in last serenity-js packege (1.10.13) is "cucumber": "1.3.2". This version isn't contain BeforeAll/AfterAll. 
Am I right that we can't use such cucumber hooks?

**Comment by jan-molak** [comment]
Hey @igTkachov - if you go with the latest alpha of Serenity/JS v2 it supports all available versions of Cucumber 1, 2, 3, 4 and 5; see [`@serenity-js/cucumber`](https://www.npmjs.com/package/@serenity-js/cucumber/v/2.0.1-alpha.81) and [examples here](https://github.com/jan-molak/serenity-js/tree/2.0/examples/).

**Comment by igTkachov** [comment]
Thank you. I didn't see info about v2.
Also I don't see reports for all tests if I use Scenario Outlines. 
In the report I see only 1 result for last value in the Example table. 
So is it fixed in v2?

**Comment by igTkachov** [comment]
Thank you, @jan-molak , unfortunately I can't find V2 before and I created a project with V1. Now I can't switch to V2. But when I'll have free time in the project, I hope to create a task for it.
