### ISSUE TITLE
Typescript 3.0 Support

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#253]
This has just released, any plans to implement it in SerenityJS?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html

**Comment by jan-molak** [comment]
Hey @marktigno! Yes, it's already on the [2.0 branch](https://github.com/jan-molak/serenity-js/commits/2.0) :-)

**Comment by marktigno** [comment]
Closing this one. It seems the current version is working with TS v3.0+. Thanks! :)
