### ISSUE TITLE
Task to create navigate to a URL

### ISSUE THREAD

**Issue by srinivasbudh** [jan-molak/serenity-js#26]
Hi,

I'm looking for a task to navigate to a URL in middle of the test execution, can any one help creating a task.

Currently we have a task to open a browser with a URL `Open.browserOn(URL)` ,

But we don't have a task to navigate to a URL in middle of a test case.

**Using selenium we can do it as below**

`driver.navigate().to("http://www.example.com")` 

**Scenario:**

A user has visited a shopping site and logged in

he want to navigate to a mobile accessories section which is possible in 2 ways
1. search for the appropriate option from menu and select
2. Directly use the deep link to navigate to that page

I want to test the second scenario so first I will start the browser with the home URL and login, now try navigating  to the  URL using deep link.

Regards
Srini

**Comment by jan-molak** [comment]
Hey @srinivasbudh!

Since it's Protractor managing the state of the browser, it's also responsible for starting it up.
What this means is that the task to `Open` simply navigates to a specific page once the browser is already up and running.

In your case you could simply write:

```typescript
describe('Navigation', function() {
    const chris = Actor.named('Chris').whoCan(BrowseTheWeb.using(protractor.browser));

    it('allows the actor to use a deep link', () => chris.attemptsTo(
        Open.browserOn('https://google.com'),
        Open.browserOn('http://example.com'),
    ));
});
```

and this would navigate between the two pages.

Having said that, you could also have your own `Navigate.to` interaction, so that the report does't say that the actor "opens the browser", but "navigates to a url":

```typescript
import { ActivityType, step } from '../../../serenity/recording';
import { Interaction, UsesAbilities } from '../../../serenity/screenplay';
import { BrowseTheWeb } from '../abilities/browse_the_web';

export class Navigate implements Interaction {

    static to = (url: string) => new Navigate(url);

    @step('{0} navigate to "#targetUrl"', ActivityType.Interaction)
    performAs(actor: UsesAbilities): PromiseLike<void> {
        return BrowseTheWeb.as(actor).get(this.targetUrl);
    }

    constructor(private targetUrl: string) { }
}
```

Does this help?
J

**Comment by srinivasbudh** [comment]
Hi,

Thanks a lot I was trying the first solution and I was facing error Webdriver has quit unexpectedly, I am able to use the second solution suggested above. Thanks for the solution.

**Comment by jan-molak** [comment]
The behaviour of both implementations is the same actually (they both call `protractor.browser.get(url)` under the hood), the only difference it how they're reported (the `@step` annotation).

Glad it helped :-)
J
