### ISSUE TITLE
Run Task in a hook

### ISSUE THREAD

**Issue by jdmesalosada** [jan-molak/serenity-js#261]
Hi everyone, 
I'm trying to run a task in a hook but I noticed that the task is not being executed.

The task has to reset the pass of the actor in the scene using an API:
```
export const SetDefaultPassToUser = (documentNumber) => Task.where('#actor restaura contrasena con un valor por defecto',
    Post.resource(setDefaultPassToUserPath, JSON.stringify({
        'documentNumber': documentNumber,
    })),
    See.if(ResponseMessage(), successfulResult())
);
```
This is my hook:

```
this.Before({ tags: ["@change_password"] }, async function () {
        return await SetDefaultPassToUser('11111111111')
    });
```

I tried using async/await but doesn't work.

Any thoughts?

Thanks in advance.

**Comment by jdmesalosada** [comment]
A quick update, I run the task inside the stage:

**Comment by jan-molak** [comment]
Hi @jdmesalosada!

You're right, the `Actor` is instantiated upon the first call to `this.stage.theActorCalled(...)`.

Have you tried the following approach:

```typescript
this.Before({ tags: ["@change_password"] }, function () {
    return this.stage.theActorCalled('admin').attemptsTo(
        SetDefaultPassToUser('11111111111')
    );
});
```

The above assumes that there is an actor called 'admin' who's capable of resetting users' permissions.
