### ISSUE TITLE
How to run a specific tag like -Dtest.tagnames=RegressionTest

### ISSUE THREAD

**Issue by rakeshnambiar** [jan-molak/serenity-js#263]
I am aware of the 'tags' option in the 'config' file which is more useful to ignore some tag. But in case the test targetting only a specific tag how can be achieved it?

**Comment by jdmesalosada** [comment]
Hi, I achieved this creating a script in my package json:

"smokeUat": "node ./node_modules/protractor/bin/protractor ./protractor.conf.js --cucumberOpts.tags=\"@uat\""

With this I only run the scripts with tag uat.

**Comment by nbarrett** [comment]
Documentation is pretty good [here](https://serenity-js.org/cucumber/execution.html#configure-protractor)!

**Comment by jan-molak** [comment]
Hey @rakeshnambiar! Does @jdmesalosada and @nbarrett suggestions solve the issue for you?

**Comment by rakeshnambiar** [comment]
Thanks @jdmesalosada @nbarrett and @jan-molak. It's worked for me. Previpously I mentioned all the required tags within a single quotes instead of  :
['~@RegressionTest', '@SanityTest']

**Comment by jan-molak** [comment]
Glad you managed to get it resolved, thanks for letting us know!
