### ISSUE TITLE
'webdriver-manager' is not recognized as an internal or external command - while executes the tests through Jenkins

### ISSUE THREAD

**Issue by rakeshnambiar** [jan-molak/serenity-js#276]
........
> webdriver-manager "update"
'webdriver-manager' is not recognized as an internal or external command

Run command used - npm run e2e-tag @smoketest

Is this related to the proxy issue?

**Comment by jan-molak** [comment]
Hi @rakeshnambiar,

This could mean one of several things:
- the [`webdriver-manager`](https://www.npmjs.com/package/webdriver-manager) npm module might not be present in `node_modules`
- the `webdriver-manager` bin script is not present in `node_modules/.bin`
- you're trying to execute `webdriver-manager` command outside the `package.json` `script` context

Does this help?
Jan

**Comment by rakeshnambiar** [comment]
Thanks a lot @jan-molak, yes you are right I was missing the webdriver-manager npm module.

Now I am facing another problem:
-------------------------------------------------------------------------------------------------------
> serenity-protractor-cucumber-pageobjects@1.0.0 test C:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script
> failsafe e2e report

[e2e] 
[e2e] > serenity-protractor-cucumber-pageobjects@1.0.0 pree2e C:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script
[e2e] > npm run webdriver:update -- --standalone false --chrome false
[e2e] 
[e2e] 
[e2e] > serenity-protractor-cucumber-pageobjects@1.0.0 webdriver:update C:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script
[e2e] > npm run webdriver-manager update "--standalone" "false" "--chrome" "false"
[e2e] 
[e2e] 
[e2e] > serenity-protractor-cucumber-pageobjects@1.0.0 webdriver-manager C:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script
[e2e] > webdriver-manager "update"
[e2e] 
[e2e] [11:50:31] I/file_manager - creating folder C:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script\node_modules\webdriver-manager\selenium
[e2e] [11:50:31] I/config_source - curl -oC:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[e2e] [11:50:31] I/config_source - curl -oC:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[e2e] [11:50:31] I/config_source - curl -oC:\Jenkins\workspace\SANITY-REGRESSION\04-DELETE-CLAIMED-ORCID\script\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[e2e] events.js:183
[e2e]       throw er; // Unhandled 'error' event
[e2e]       ^
[e2e] 
[e2e] Error: read ECONNRESET
[e2e]     at TLSWrap.onread (net.js:622:25)
[e2e] npm ERR! code ELIFECYCLE
[e2e] npm ERR! errno 1
[e2e] npm ERR! serenity-protractor-cucumber-pageobjects@1.0.0 webdriver-manager: `webdriver-manager "update"`
[e2e] npm ERR! Exit status 1
[e2e] npm ERR! 
[e2e] npm ERR! Failed at the serenity-protractor-cucumber-pageobjects@1.0.0 webdriver-manager script.
[e2e] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
-------------------------------------------------------------------------------------------------------

As you could see above I have changed the "pree2e": "npm run webdriver:update -- --standalone --versions.standalone=2.53.1 --versions.chrome=2.29" to  "pree2e": "npm run webdriver:update -- --standalone false --chrome false" based on some forum. But still no hope. Also added, strict-ssl=false
registry=http://registry.npmjs.org/ on .npmrc file.

Most interesting thing, when I execute the script manually on the Jenkins-Slave (windows VM) it's working without any error. However, trying through Jenkins causing the problem.

**Comment by rakeshnambiar** [comment]
@jan-molak could you please advise on the above issue?

**Comment by rakeshnambiar** [comment]
It's resolved now using --ignore_ssl --proxy 

    "webdriver-manager": "webdriver-manager update --ignore_ssl --proxy",
    "webdriver:update": "npm run webdriver-manager"
