### ISSUE TITLE
Reference Issue - Master Table.

### ISSUE THREAD

**Issue by yogi1916** [jan-molak/serenity-js#277]
Data Structure :
![image](https://user-images.githubusercontent.com/37954820/47629294-48d40d00-db60-11e8-8983-951a80db4fc8.png)

Issue: Not getting **Code** - need to display in grid

namespace QuickQuotationTool.Quotation.Entities
{
    using QuickQuotationTool.Master.Entities;
    using QuickQuotationTool.Web.Modules.Quotation.QuotationLabour;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;
    using static MVC.Views.Master;

    [ConnectionKey("Northwind"), Module("Quotation"), TableName("[dbo].[QuotationLabour]"), TwoLevelCached]
    [DisplayName("Quotation Labour"), InstanceName("Quotation Labour")]
    //[LeftJoin("cd1", "refLabourMaster", "cd.[IdLabourMaster] = t0.[IdLabourMaster]", RowType = typeof(PartsSubCategoryRow), TitlePrefix = "")]
    [ReadPermission("Administration:General")]
    //[LeftJoin("jPartsLabourMaster", "refLabourMaster", "t.IdLabourMaster = T0.IdLabourMaster")]
    [ModifyPermission("Administration:General")]

    public sealed class QuotationLabourRow : Row, IIdRow
    {

        [DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }
        [DisplayName("Id"), ForeignKey("[dbo].[refLabourMaster]", "IdLabourMaster"), LeftJoin("jPartsLabourMaster"), TextualField("IdLabourMasterCode"), LookupEditor(typeof(RefLabourCategoryLookUp))]
        public Int32? IdLabourMaster
        {
            get { return Fields.IdLabourMaster[this]; }
            set { Fields.IdLabourMaster[this] = value; }
        }      
        [DisplayName("Id Quotation"), NotNull, ForeignKey("[dbo].[Quotation]", "QuotationId"), LeftJoin("jIdQuotation"), TextualField("IdQuotationTitle")]
        public Int32? IdQuotation
        {
            get { return Fields.IdQuotation[this]; }
            set { Fields.IdQuotation[this] = value; }
        }        

        [DisplayName("Service Hours"), NotNull]
        public Int32? ServiceHours
        {
            get { return Fields.ServiceHours[this]; }
            set { Fields.ServiceHours[this] = value; }
        }

        [DisplayName("Cost"), Size(5), Scale(2), NotNull]
        public Decimal? Cost
        {
            get { return Fields.Cost[this]; }
            set { Fields.Cost[this] = value; }
        }

        [DisplayName("Should Visible On Quote Print"), NotNull]
        public Boolean? ShouldVisibleOnQuotePrint
        {
            get { return Fields.ShouldVisibleOnQuotePrint[this]; }
            set { Fields.ShouldVisibleOnQuotePrint[this] = value; }
        }       
    
        [DisplayName("Id Labour Master Id Company"), Expression("jPartsLabourMaster.[IdCompany]")]
        public Int32? IdLabourMasterIdCompany
        {
            get { return Fields.IdLabourMasterIdCompany[this]; }
            set { Fields.IdLabourMasterIdCompany[this] = value; }
        }
        [DisplayName("Category"), NotNull, ForeignKey("[dbo].[RefLabourCategory]", "IdCategory"), Expression("jPartsLabourMaster.[IdCategory]"), LeftJoin("jCategory"), TextualField("Title"), LookupInclude]
        public Int32? IdCategory
        {
            get { return Fields.IdCategory[this]; }
            set { Fields.IdCategory[this] = value; }
        }
        [DisplayName("Code"), Expression("cd.[Code]")]
        public String RefLabourCategoryCode
        {
            get { return Fields.RefLabourCategoryCode[this]; }
            set { Fields.RefLabourCategoryCode[this] = value; }
        }
        [DisplayName("Id Labour Master Id Category"), Expression("jPartsLabourMaster.[IdCategory]")]
        public Int32? IdLabourMasterIdCategory
        {
            get { return Fields.IdLabourMasterIdCategory[this]; }
            set { Fields.IdLabourMasterIdCategory[this] = value; }
        }

        [DisplayName("Id Labour Master Code"), Expression("jPartsLabourMaster.[Code]")]
        public String Code
        {
            get { return Fields.Code[this]; }
            set { Fields.Code[this] = value; }
        }

        [DisplayName("Id Labour Master Description"), Expression("jPartsLabourMaster.[Description]")]
        public String IdLabourMasterDescription
        {
            get { return Fields.IdLabourMasterDescription[this]; }
            set { Fields.IdLabourMasterDescription[this] = value; }
        }

        [DisplayName("Id Labour Master Is Active"), Expression("jPartsLabourMaster.[IsActive]")]
        public Boolean? IdLabourMasterIsActive
        {
            get { return Fields.IdLabourMasterIsActive[this]; }
            set { Fields.IdLabourMasterIsActive[this] = value; }
        }

        [DisplayName("Id Quotation Title"), Expression("jIdQuotation.[Title]")]
        public String IdQuotationTitle
        {
            get { return Fields.IdQuotationTitle[this]; }
            set { Fields.IdQuotationTitle[this] = value; }
        }

        [DisplayName("Id Quotation Description"), Expression("jIdQuotation.[Description]")]
        public String IdQuotationDescription
        {
            get { return Fields.IdQuotationDescription[this]; }
            set { Fields.IdQuotationDescription[this] = value; }
        }

        [DisplayName("Id Quotation Client"), Expression("jIdQuotation.[Client]")]
        public String IdQuotationClient
        {
            get { return Fields.IdQuotationClient[this]; }
            set { Fields.IdQuotationClient[this] = value; }
        }

        [DisplayName("Id Quotation Quotation Date"), Expression("jIdQuotation.[QuotationDate]")]
        public DateTime? IdQuotationQuotationDate
        {
            get { return Fields.IdQuotationQuotationDate[this]; }
            set { Fields.IdQuotationQuotationDate[this] = value; }
        }

        [DisplayName("Id Quotation Valid To Date"), Expression("jIdQuotation.[ValidToDate]")]
        public DateTime? IdQuotationValidToDate
        {
            get { return Fields.IdQuotationValidToDate[this]; }
            set { Fields.IdQuotationValidToDate[this] = value; }
        }

        [DisplayName("Id Quotation State"), Expression("jIdQuotation.[State]")]
        public Int32? IdQuotationState
        {
            get { return Fields.IdQuotationState[this]; }
            set { Fields.IdQuotationState[this] = value; }
        }
        [DisplayName("Line Total"), Expression("(t0.[Cost] * t0.[ServiceHours])")]
        [AlignRight, DisplayFormat("#,##0.00"), MinSelectLevel(SelectLevel.List)]
        public Decimal? LineTotal
        {
            get { return Fields.LineTotal[this]; }
            set { Fields.LineTotal[this] = value; }
        }
        [DisplayName("Id Quotation Is Current Version"), Expression("jIdQuotation.[IsCurrentVersion]")]
        public Boolean? IdQuotationIsCurrentVersion
        {
            get { return Fields.IdQuotationIsCurrentVersion[this]; }
            set { Fields.IdQuotationIsCurrentVersion[this] = value; }
        }

        [DisplayName("Id Quotation Customer Id"), Expression("jIdQuotation.[CustomerID]")]
        public String IdQuotationCustomerId
        {
            get { return Fields.IdQuotationCustomerId[this]; }
            set { Fields.IdQuotationCustomerId[this] = value; }
        }

        [DisplayName("Id Quotation Validity In Days"), Expression("jIdQuotation.[ValidityInDays]")]
        public Int32? IdQuotationValidityInDays
        {
            get { return Fields.IdQuotationValidityInDays[this]; }
            set { Fields.IdQuotationValidityInDays[this] = value; }
        }

        [DisplayName("Id Quotation Margin Percentage"), Expression("jIdQuotation.[MarginPercentage]")]
        public Decimal? IdQuotationMarginPercentage
        {
            get { return Fields.IdQuotationMarginPercentage[this]; }
            set { Fields.IdQuotationMarginPercentage[this] = value; }
        }

        [DisplayName("Id Quotation Revison Number"), Expression("jIdQuotation.[RevisonNumber]")]
        public String IdQuotationRevisonNumber
        {
            get { return Fields.IdQuotationRevisonNumber[this]; }
            set { Fields.IdQuotationRevisonNumber[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public QuotationLabourRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {

            public Int32Field Id;
            public Int32Field IdCategory;
            public Int32Field IdLabourMaster;
            public Int32Field IdQuotation;

            public Int32Field ServiceHours;

            public DecimalField Cost;

            public BooleanField ShouldVisibleOnQuotePrint;

            public Int32Field IdLabourMasterIdCompany;

            public Int32Field IdLabourMasterIdCategory;

            public StringField Code;

            public StringField IdLabourMasterDescription;

            public BooleanField IdLabourMasterIsActive;

            public StringField IdQuotationTitle;

            public StringField IdQuotationDescription;

            public StringField IdQuotationClient;

            public DateTimeField IdQuotationQuotationDate;

            public DateTimeField IdQuotationValidToDate;

            public Int32Field IdQuotationState;

            public BooleanField IdQuotationIsCurrentVersion;

            public StringField IdQuotationCustomerId;

            public Int32Field IdQuotationValidityInDays;

            public DecimalField IdQuotationMarginPercentage;

            public StringField IdQuotationRevisonNumber;

            public DecimalField LineTotal;
            public StringField RefLabourCategoryCode;
            public StringField CodeName;
        }
    }
}](url)

**Comment by jan-molak** [comment]
Hi @yogi1916 and welcome to the Serenity/JS community! The code you've pasted above looks like C#, so I'm not sure if you meant to raise a ticket for this project (a TypeScript acceptance testing library)?
