### ISSUE TITLE
Unable to override the baseURL from the command line

### ISSUE THREAD

**Issue by rakeshnambiar** [jan-molak/serenity-js#278]
I am trying to use multiple URLs for the same script and using the below command to execute the tests.

npm run e2e -baseUrl http://your.other.url.com -tag @Regression

OR

npm run e2e --baseUrl http://your.other.url.com --tag @Regression

I end up with 'Error: Error: more than one config file specified'. Please advise.

**Comment by marktigno** [comment]
@rakeshnambiar you need to add `--` before the `--baseUrl` in order to override that.
ex. `npm run e2e -- --baseUrl="http://www.somewebsite.com" --cucumberOpts.tags="@Regression"`

**Comment by rakeshnambiar** [comment]
Thanks dear @marktigno it's worked.
