### ISSUE TITLE
Verifying sorted elements

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#280]
Hello all! Is there any way to verify if the elements on a webpage is sorted? I'm trying to integrate `chai-sorted` on my test but it does not yet support TypeScript's type definition on that module. Thanks!

**Comment by jan-molak** [comment]
Hey @marktigno! I haven't used `chai-sorted` myself, so can't really comment on it I'm afraid. It [doesn't seem](https://github.com/johntimothybailey/chai-sorted/blob/master/lib/chai-sorted.js) too involved, though, so you might want to consider creating a `.d.ts` file describing the `chai-sorted` assertions in your project, or perhaps contributing a definition to the DefinitelyTyped project? [Type definitions for `chai-things`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/chai-things/index.d.ts) might provide inspiration.

Does this help at all?
Jan

**Comment by marktigno** [comment]
Hello @jan-molak! Hmm... I think I try to get a shot to create a `.d.ts` for chai-sorted. Thanks for giving me an idea! :)

**Comment by marktigno** [comment]
Hello @jan-molak, I finally manage to create a sort checker on SerenityJS. Here is an example code that I used:

    export class Sorted implements Question<PromiseLike<boolean>> {
        public static check(target: Target, order: string): Sorted {
            return new Sorted(target, order);
        }
        answeredBy(actor: UsesAbilities): PromiseLike<boolean> {
            let allEqual: boolean;
            const ord: string = this.order;

            const unsorted = BrowseTheWeb.as(actor).locateAll(this.target).map(function(element) {
                return element.getText().then(value => value.split(' '));
            });

            const sorted = unsorted.then(function(texts) {
                if (ord === "asc") {
                    return texts.sort();
                } else if (ord === "desc") {
                    return texts.sort().reverse();
                }
            });

            const equals = protractor.promise.all([unsorted, sorted]).then(function(texts) {
                const unsorted2 = texts[0];
                const sorted2 = texts[1];
                allEqual = (unsorted2.length === sorted2.length);
                sorted2.forEach(function(sortedItem, i) {
                    allEqual = allEqual && (sortedItem === unsorted2[i]);
                });
                return allEqual;
            });
            return equals;
        }

        toString = () => `the elements ${this.target} if sorted in ${this.order}`;

        constructor(private target: Target, private order: string) {}
    }

**Comment by jan-molak** [comment]
Nice one! Thanks for letting me know :-)
