### ISSUE TITLE
"This file was not a valid JSON Serenity test report" error message

### ISSUE THREAD

**Issue by san-ouadghiri** [jan-molak/serenity-js#281]
Hi @jan-molak,

Since a few weeks I have the below java error. Since a few days I have 2 warns I did not have before about the .json files not being relevant serenity test reports ones.

```
[failsafe] Script 'all:chrome' exited with code 100
[report] 
[report] > integration-tests@1.0.18 report /home/myprojectpath
[report] > serenity run
[report] 
[report] info: Using Java at: /usr/bin/java
[report] TypeError: Cannot read property '0' of undefined
[report]     at checkJavaHome.then.catch.then.then.catch.then.std (/home/myprojectpath/node_modules/java-home/lib/java-home.js:92:27)
[report]     at process._tickCallback (internal/process/next_tick.js:68:7)
[report]     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
[report]     at startup (internal/bootstrap/node.js:285:19)
[report]     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[report] warn: net.thucydides.core.reports.json.JSONTestOutcomeReporter - This file was not a valid JSON Serenity test report: 1cf3dc08679f3ecf62d7c2d3ec01a353.json
[report] warn: net.thucydides.core.reports.json.JSONTestOutcomeReporter - This file was not a valid JSON Serenity test report: 1cf3dc08679f3ecf62d7c2d3ec01a353.json
[report] info: All done!
[failsafe] Script 'report' exited with code 0

```

Is it a serenityjs <-> java reporter regression? Or shall I look at anything I could have done wrong on my side?

**Comment by jan-molak** [comment]
Hey @san-ouadghiri! Could you please paste the (anonymised) contents of `1cf3dc08679f3ecf62d7c2d3ec01a353.json`?

**Comment by cmorris1** [comment]
Hello,
I have a similar error. 
I have attached the file. Appears to be malformed json.

[1cf3dc08679f3ecf62d7c2d3ec01a353.txt](https://github.com/jan-molak/serenity-js/files/2601021/1cf3dc08679f3ecf62d7c2d3ec01a353.txt)

**Comment by jan-molak** [comment]
Thanks, this might happen when a Serenity/JS task is not correctly synchronised with other promises.

Compare the below:
```typescript
this.When('she books the flight', function() {
  this.stage.theActorInTheSpotlight().attemptsTo(BookTheFlight());
});
```
with:
```typescript
this.When('she books the flight', function() {
  return this.stage.theActorInTheSpotlight().attemptsTo(BookTheFlight());
});
```

The lack of the `return` statement in the first implementation causes the actor to execute the task outside of the Cucumber promise chain.

My first instinct would be to go through the step library and look for any missing `return` statements.

Does this help?
Jan

**Comment by cmorris1** [comment]
Thank you. That helped.
In some steps I did not return and in some I am returning regular Chai as Promised assertions.
I suppose all returns should be of screenplay Actor operations. 
Is that true?

**Comment by jan-molak** [comment]
Excellent, I'm glad it helped. 

> I suppose all returns should be of screenplay Actor operations.

Yes, all the cucumber steps where the actor performs their tasks should return the `actor.attemptsTo` chain

> in some I am returning regular Chai as Promised assertions.

Have a look at the (Serenity/JS Handbook: Assertions](https://serenity-js.org/design/assertions.html); the best way to use the `chai-as-promised` assertions from within the `See.if` task.

**Comment by Manishrn** [comment]
Hi @jan-molak 

I am also getting the same error, I have checked all return statements etc.
Is there somethig that I have missed. 
I have attached scenario_report as well as step file

[Book_Apoointment_steps.txt](https://github.com/jan-molak/serenity-js/files/4029893/Book_Apoointment_steps.txt)


[scenario-report-41680d5c18cec7626ccbdd26645668b0.txt](https://github.com/jan-molak/serenity-js/files/4029884/scenario-report-41680d5c18cec7626ccbdd26645668b0.txt)

**Comment by jan-molak** [comment]
Hey @Manishrn, it looks like the steps library uses a mixture of different step definition styles, misses the return statement in the `background information contains speciality` step, and doesn't use the actor in verification steps:

```typescript
  this.Given(/^that BookPr is on appointments page$/, async () => {
    return await BookPr.attemptsTo(SingleAppointment.onAppointmentPage());
  });  
  
  this.When(/^BookPr starts to book appointment$/, async () => {
    return await BookPr.attemptsTo(BookSingleAppointment.createSingleAppointment());
  })

  this.Then(/^single booking page should be visible$/, function () {
    
     return Ensure.that(Text.of(NewAppointmentComponent.AppointmentText),equals('Appointments'));
  })

  this.When(/^background information contains speciality$/, async ()=>{
    
     Ensure.that(Text.of(NewAppointmentComponent.AppointmentText),equals('Appointments'));    
  })
```

Try this implementation instead:

```typescript
  this.Given(/^that BookPr is on appointments page$/, function () {
    return BookPr.attemptsTo(
      SingleAppointment.onAppointmentPage()
    );
  });  
  
  this.When(/^BookPr starts to book appointment$/, function () {
    return BookPr.attemptsTo(
      BookSingleAppointment.createSingleAppointment()
    );
  })

  this.Then(/^single booking page should be visible$/, function () {
    return BookPr.attemptsTo(
      Ensure.that(Text.of(NewAppointmentComponent.AppointmentText), equals('Appointments')),
    );
  });

  this.When(/^background information contains speciality$/, function () {
    return BookPr.attemptsTo(
      Ensure.that(Text.of(NewAppointmentComponent.AppointmentText),equals('Appointments'))
    );    
  });
```

Hope this helps!
Jan

**Comment by Manishrn** [comment]
@jan-molak :

I tried with step you have given, but no luck.

-Manish

**Comment by sumithkhandelwal** [comment]
Verify that the Scenario Outline has the information regards the scenario and run again and see.
