### ISSUE TITLE
[e2e] Cannot read property 'lutimes' of undefined

### ISSUE THREAD

**Issue by abhinaba1080** [jan-molak/serenity-js#286]
Hi All, 
I am using exactly same package.json and conf file same as :
https://github.com/jan-molak/serenity-js/tree/master/examples/todomvc-protractor-cucumber-pageobjects
When I am executing the npm test with "protractor-cucumber-framework", the test run absolutely fine, but when i am replacing it with serenity-js framework in conf file , It throws the error like:
**[e2e] Cannot read property 'lutimes' of undefined**
.

FYI: i have not use any variable/set/keyword called "lutimes"
The control is not even checking the feature file content, it simply throw the error before checking the feature file. 
**The only reference of "lutimes" i found out is in a lib file called "polyfills.js" .i am executing the test in my windows machine machine under company proxy. Please suggest me if i can change any lib code to make the execution possible.**

**Comment by abhinaba1080** [comment]
@jan-molak, I have done a small research and found out that this polyfills.js is situated under "graceful-fs" package. Why graceful-js is required for serenity to execute test cases? is there any way that i can mute the graceful-js pack and run the scripts? please suggest

Many thanks in advance.

**Comment by abhinaba1080** [comment]
issue solved after re-installing serenity-js from core

**Comment by jan-molak** [comment]
Glad you figured it out, thanks for letting us know!
