### ISSUE TITLE
post test cleanup with screenplay

### ISSUE THREAD

**Issue by scaddenp** [jan-molak/serenity-js#313]
I am trying to see how you can get code to execute on completion of test. (after the "then" steps when running through cucumber).

The context is around security testing. The application provides different resources and functionality depending on what authorities are granted with authentication. Rather than have a bunch of "test users" defined (which necessarily have to exist on production), with all the issues of password management, we are looking at have a single test user in the system and granting the testing rights just before authentication and then revoking them again at end. We have api which does this which requires only one pass token to manage and more crucially, the api is cannot be executed externally.
Setup is easy - each actor gets ability which defines the authorities to grant and executed within the authenticate phase.

But how do you take down? In a more traditional testing framework, this is the tear down phase. With Serenity running through junit, its easy. Can you do this with serenity/js? What I dont want is the test user left with elevated privileges if a test fails.

**Comment by jan-molak** [comment]
Is this teardown something you're planning on doing after every scenario? If that's the case perhaps Cucumber's [`After` hook](https://github.com/cucumber/cucumber-js/blob/1.x/features/after_hook_interface.feature) could help?

**Comment by scaddenp** [comment]
I only need it for the security testing but I guess the hook is the only safe mechanism. Ideally I would be able to reference the actor in the spotlight in the @after hook but that looks tough. 
...
Hmm, looks like can reference the stage in a hook.
return this.stage.theActorInTheSpotlight()
This should work.
