### ISSUE TITLE
Gherkin 4.1.0 and above not working with Serenity/JS

### ISSUE THREAD

**Issue by metrophos** [jan-molak/serenity-js#32]
Hi!

Serenity/JS works only with gherkin-javascript 4.0.0 (https://github.com/cucumber/gherkin-javascript).
The package comes with cucumber 1.3.1. Cucumber has the package as dependency (^4.0.0) configured.

With Gherkin version 4.1.0 and above following error occurs:

> 14:45:19.750 | SceneFinished: xxxx (result: FAILURE, error:TypeError: Path must be a string. Received undefined)
> 
> Failures:
> 
> [14:45:19] E/launcher - Error: TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.relative (path.js:1227:5)
>     at .../node_modules/serenity-js/src/serenity/reporting/serenity_bdd_reporter.ts:89:38
> [14:45:19] E/launcher - Process exited with error code 100

I fixed this for now by adding the gherkin-javascript package to my dependencies with version 4.0.0

Hope you can fix the actual error.

Regards,
Daniel

**Comment by jan-molak** [comment]
Hey Daniel and thanks for reporting the issue! Would you be able to put together an example test case? (Could be a mini-project on github; something I can run locally to reproduce the problem).

Thanks,
Jan

**Comment by jan-molak** [comment]
This issue has been [resolved in Cucumber 1.3.2](https://github.com/cucumber/cucumber-js/pull/793). Kudos to @charlierudolph and @jbpros for sorting it out so quickly!

@metrophos, @johnlister could you please update Cucumber and let me know if it's all working for you now?

**Comment by metrophos** [comment]
Hi @jan-molak!

I have updated my project and now it works as expected.
Thank you for the very fast support!

**Comment by jan-molak** [comment]
No problem at all, glad it helped!
