### ISSUE TITLE
Need Puppeteer integration with Serenity js

### ISSUE THREAD

**Issue by abhinaba1080** [jan-molak/serenity-js#322]
Hi Jan,

we are using puppeteer-cucumber for testing our react app.  Can we produce serenity report with the current tool stake? 

Any guidance will lead us achieve success. 

Many thanks in advance.

**Comment by jan-molak** [comment]
Hi @abhinaba1080! Sure, you can do that with Serenity/JS version 2 (currently in alpha, but the reporting functionality has been finalised).

Have a look at [this example](https://github.com/jan-molak/serenity-js/tree/2.0/examples/cucumber-reporting) on the 2.0 branch and please note that it uses the `@serenity-js` modules version `2.0.1-alpha.68` (as opposed to the examples on `master` which use version 1.x).

There's no puppeteer-specific Screenplay implementation yet, but you should be able to get the basic reports working fine.

Let me know how it goes!

Jan

**Comment by abhinaba1080** [comment]
Thanks
