### ISSUE TITLE
Any react selector available for Protractor +Serenity setup? 

### ISSUE THREAD

**Issue by abhinaba1080** [jan-molak/serenity-js#327]
Hi @jan-molak,
I am using serenity 1.x + cucumber 1.x setup. I was wondering that if we have some cool plugins like  React selector for protractor /serenity-js. It will help to find out react elements by props (or react specific tags) and make a robust page object model. 
any leads will be appreciated. Thanks in advance.

**Comment by jan-molak** [comment]
Hi @abhinaba1080 - I'm not aware of the React selector plugin for protractor; If you could provide me with a link I could have a look and suggest?

**Comment by abhinaba1080** [comment]
Hi @jan-molak , I searched a git repo where author tried to extend the 'resq' module to establish the connection between protractor and react selector. Due to lack of the examples and documents, its really hard to figure it out how it works. If you can look into it and provide some idea, it will be really helpful. 

repo: https://github.com/vitalics/protractor-react-plugin

**Comment by abhinaba1080** [comment]
Hi @jan-molak :

I have created one React selector plugin for protractor [protractor-react-selector](https://www.npmjs.com/package/protractor-react-selector)

It will help test developers to find out web elements by using react components directly using props and states...

Your thoughts will be valuable...

**Comment by abhinaba1080** [comment]
Hi @jan-molak , I have invested a lot of time in this area. Finally came up with a npm module. Now, protractor can be used efficiently to find out React elements by React Component and props. 

More information is here: 
https://medium.com/@abhinabaghosh.1994/test-your-react-app-efficiently-with-protractor-b8406db9148f

Your feedback will make my day! :)
