### ISSUE TITLE
Unknown command error: unknown command: Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#329]
I have updated our chrome driver to version 75.0.3770.90. It works on Windows when using directConnect on the config but when we run it on selenium grid, some calls are not working as what mentioned on this issue. Is there a way to fix this problem? Thanks! :)

**Comment by jan-molak** [comment]
Hey @marktigno! This looks like either a chromedriver or protractor-related issue and I haven't come across it yet I'm afraid;

Having said that, I've been using the npm [chromedriver](https://www.npmjs.com/package/chromedriver) package to get chromedriver instead of the webdriver-manager and have configured Protractor as follows:

```javascript
exports.config = {
    chromeDriver: require('chromedriver/lib/chromedriver').path,
    SELENIUM_PROMISE_MANAGER: false,
    directConnect: true,

    // etc.
}
```

**Comment by marktigno** [comment]
Hello @jan-molak,

Thanks for the reply. I think I have found the solution but I don't know if I can set this to the protractor config file. I don't know if capable to set `wc3 mode` to `false`? Here a stackoverflow [link.](https://stackoverflow.com/questions/56111529/cannot-call-non-w3c-standard-command-while-in-w3c-mode-seleniumwebdrivererr)

**Comment by jan-molak** [comment]
I see there's an unresolved ticket raised for Protractor here angular/protractor#4990.
The OP mentions that he's using Selenium v. 4.0.0-alpha.1, is that what you're on, @marktigno?

**Comment by marktigno** [comment]
We are still using selenium v. 3.141.59 on our test automation machines.

**Comment by marktigno** [comment]
Hello @jan-molak, I think I found the solution for this issue: https://github.com/angular/protractor/issues/5261#issuecomment-502768889
I can close this ticket since our automation scripts are now working again. Thanks! :)
