### ISSUE TITLE
Tag @Manual support

### ISSUE THREAD

**Issue by metrophos** [jan-molak/serenity-js#33]
Hi!

Is in the future a plan to support the @Manual Tag. The behavior should be that Scenarios or Features with this annotation are in the report but not executed by the Test Framework like Cucumber. 

For now my workaround is that i don't implement de Given When Then sentences in my step definitions and use @Manual on the Scenarios and Features to generate reports with manual tests. The problem here is that i always must use different sentences for my manual tests and cucumber report me that i must implement the step definitions. 

For a better workaround: Is there a way to get the current tag annotation from a step definition like:
```
    this.Given(/^test$/, () => {
        let tags = serenity.getTags();
    });
```
 If yes, I can use a if statement to run a step or not depend on the tag.

http://thucydides.info/docs/serenity-staging/:
> Row Manual contains manual tests. In order to execute test manually you should use @Manual annotation, idea the same as for Automated row. Generally, it is possible to use it to mark scenarios (@Manual on scenario level) or all scenarios in story (@manual on Story level). The @Manual annotation is not designed to be defined for an individual step within a test, but only for the whole test.

Regards,
Daniel

**Comment by jan-molak** [comment]
Hi Daniel,

Manual tags are reported as of [@serenity-js/core 1.5.2](https://github.com/jan-molak/serenity-js/commit/babc5878ebc6e9be4686df1419c52c49298b32f7).

Best,
Jan

**Comment by metrophos** [comment]
Hi Jan,

Thank you for your investigation! I want to upgrade my project to check it but have now another issue.

It's exactly the same issue and behavior which has @sabau described in https://github.com/jan-molak/serenity-js/issues/84 in the last comment.

Regards,
Daniel

**Comment by jan-molak** [comment]
Cool, thanks for letting me know, I'm happy that it's working for you. I responded to your comment on #84 there, so closing this issue.

**Comment by metrophos** [comment]
Hi Jan,

Thanks again, [@manual]() works fine. Perhaps one improvement. Can you support [@Manual]() too. 

I mean with a capital M?

**Comment by jan-molak** [comment]
Cool, thanks for letting me know. I think you're right, the case of the tag should not matter (so Manual == manual, Jira == jira, etc.) Would you mind raising a separate ticket for that?

Thanks!
Jan

**Comment by abhinaba1080** [comment]
@jan-molak Does this work for Non-Screenplay scenarios as well?
