### ISSUE TITLE
Need clarification for Screenshot configuration

### ISSUE THREAD

**Issue by abhinaba1080** [jan-molak/serenity-js#335]
@jan-molak 

Need a clarification, is there any screenshot configuration in Serenity-js (V1) like Serenity (Java version)

serenity.take.screenshots.for.tasks=after_each_step
serenity.take.screenshots.for.interactions=for_failure
serenity.take.screenshots.for.questions=after_each_step

Side Note: I am using :
        "serenity-cli": "^0.1.4",
        "serenity-js": "1.10.13",

**Comment by jan-molak** [comment]
Hey @abhinaba1080! Yes, Serenity/JS V1 has a mechanism similar to Serenity BDD.
Here are the [specs](https://github.com/jan-molak/serenity-js/blob/master/packages/serenity-js/spec/api/serenity-protractor/stage/photographer.spec.ts#L336-L355), here's an [example `protractor.conf.js`](https://github.com/jan-molak/serenity-js/blob/5fa1057f34907da5c2f1dcd1030c7c08d7b5687a/examples/todomvc-protractor-mocha/protractor.conf.js), and here's how it works:

```javascript
// protractor.conf.js

const crew = require('serenity-js/lib/stage_crew');

exports.config = {

    framework: 'custom',
    frameworkPath: require.resolve('serenity-js'),

    serenity: {
        crew: [
            crew.Photographer.who(_ => _
                .takesPhotosOf(_.Tasks_and_Interactions)  // or _.Failures
                .takesPhotosWhen(_.Activity_Finishes)     // or _.Activity_Starts_and_Finishes, or _.Activity_Starts
            ),
            // ... 
        ]
    },

    // other config omitted for brevity
}
```

Hope this helps!
Jan

**Comment by abhinaba1080** [comment]
> Hey @abhinaba1080! Yes, Serenity/JS V1 has a mechanism similar to Serenity BDD.
> Here are the [specs](https://github.com/jan-molak/serenity-js/blob/master/packages/serenity-js/spec/api/serenity-protractor/stage/photographer.spec.ts#L336-L355), here's an [example `protractor.conf.js`](https://github.com/jan-molak/serenity-js/blob/5fa1057f34907da5c2f1dcd1030c7c08d7b5687a/examples/todomvc-protractor-mocha/protractor.conf.js), and here's how it works:
> 
> ```js
> // protractor.conf.js
> 
> const crew = require('serenity-js/lib/stage_crew');
> 
> exports.config = {
> 
>     framework: 'custom',
>     frameworkPath: require.resolve('serenity-js'),
> 
>     serenity: {
>         crew: [
>             crew.Photographer.who(_ => _
>                 .takesPhotosOf(_.Tasks_and_Interactions)  // or _.Failures
>                 .takesPhotosWhen(_.Activity_Finishes)     // or _.Activity_Starts_and_Finishes, or _.Activity_Starts
>             ),
>             // ... 
>         ]
>     },
> 
>     // other config omitted for brevity
> }
> ```
> 
> Hope this helps!
> Jan

Really helped. Thanks a ton!

**Comment by abhinaba1080** [comment]
@jan-molak : can you suggest the same for Serenity-js 2:

I have recently migrated to serenity-js 2 . It works for me but there is no screenshot in the report. 

How to modify the below to take screenshots in different scenario: 

serenity: {
    crew: [new ArtifactArchiver(new FileSystem(new Path('./target/site/serenity'))), new SerenityBDDReporter(), new ConsoleReporter()]
  }

**Comment by jan-molak** [comment]
@abhinaba1080 - sure thing!

```javascript
const { Photographer, TakePhotosOfInteractions } = require('@serenity-js/protractor');

// ...
serenity: {
  crew: [
    ArtifactArchiver.storingArtifactsAt('./target/site/serenity')),       // <- there's a factory method for this one now
    new SerenityBDDReporter(),
    Photographer.whoWill(TakePhotosOfInteractions), // or TakePhotosBeforeAndAfterInteractions, or TakePhotosOfFailures, 
  ]
}
```

Does this help?

**Comment by abhinaba1080** [comment]
Really helps.. you are a true avenger! :)

**Comment by abhinaba1080** [comment]
It really helps.. Just a quick check: do we have something like @types/serenity-js or something like that for typescript support? i want to migrate all require statements into imports.

**Comment by abhinaba1080** [comment]
> ```js
> Photographer.whoWill(TakePhotosOfInteractions)
> ```

Getting error. 

```
[12:57:31] E/configParser - Error code: 105
[12:57:31] E/configParser - Error message: failed loading configuration file transform/config/browser/chrome.config.js
[12:57:31] E/configParser - TypeError: Photographer.whoWill is not a function
    at Object.<anonymous> (C:\Dev Room\Projects\ArcherBDDUITests\transform\config\browser\chrome.config.js:22:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ConfigParser.addFileConfig (C:\Dev Room\Projects\ArcherBDDUITests\node_modules\protractor\built\configParser.js:135:26)
    at Object.initFn [as init] (C:\Dev Room\Projects\ArcherBDDUITests\node_modules\protractor\built\launcher.js:93:22)
```

**Comment by abhinaba1080** [comment]
> > ```js
> > Photographer.whoWill(TakePhotosOfInteractions)
> > ```
> 
> @jan-molak Now i have two problems:
> 
> 1. Getting error for above
> 
> ```
> [12:57:31] E/configParser - Error code: 105
> [12:57:31] E/configParser - Error message: failed loading configuration file transform/config/browser/chrome.config.js
> [12:57:31] E/configParser - TypeError: Photographer.whoWill is not a function
>     at Object.<anonymous> (C:\Dev Room\Projects\ArcherBDDUITests\transform\config\browser\chrome.config.js:22:26)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at ConfigParser.addFileConfig (C:\Dev Room\Projects\ArcherBDDUITests\node_modules\protractor\built\configParser.js:135:26)
>     at Object.initFn [as init] (C:\Dev Room\Projects\ArcherBDDUITests\node_modules\protractor\built\launcher.js:93:22)
> ```
> 
> 1. my dependencies are:
> 
> ```
> 
>     "@serenity-js/core": "next",
>     "@serenity-js/protractor": "next",
>     "@serenity-js/cucumber": "next",
>     "cucumber": "^5.1.0",
>      "protractor": "5.4.2",
> ```
> 
> It shows npm warning like:
> 
> ```
> 
> npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/core@2.x but none is installed. You must install peer dependencies yourself.
> npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/cucumber@2.x but none is installed. You must install peer dependencies yourself.
> npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/jasmine@2.x but none is installed. You must install peer dependencies yourself.
> npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/mocha@2.x but none is installed. You must install peer dependencies yourself.
> ```
> 
> Side note: my config looks like below:
> 
> ```
> import { browser, Config } from 'protractor';
> import { ArtifactArchiver, ConsoleReporter, SerenityBDDReporter } from '@serenity-js/core';
> import { Photographer, TakePhotosOfInteractions } from '@serenity-js/protractor';
> 
> export const config: Config = {
>   // seleniumAddress: "http://INENGHOSHA1L1C:4444/wd/hub",
>   // SELENIUM_PROMISE_MANAGER: false,
> 
>   framework: 'custom',
>   frameworkPath: require.resolve('@serenity-js/protractor/adapter'),
> 
>   baseUrl: 'http://localhost:3000',
> 
>   allScriptsTimeout: 110000,
> 
>   specs: [rootPath + '/test/e2e/features/**/*.feature'],
>   serenity: {
>     crew: [
>       ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
>       new SerenityBDDReporter(),
>       Photographer.whoWill(TakePhotosOfInteractions),
>       new ConsoleReporter()
>     ]
>   },
>   cucumberOpts: {
>     require: [rootPath + '/transform/**/*.js'],
>     format: 'pretty',
>     compiler: 'ts:ts-node/register'
>   },
> 
>   capabilities: {
>     browserName: 'chrome',
>     chromeOptions: {
>       useAutomationExtension: false,
>       args: ['--disable-gpu', '--disable-extensions']
>     }
> 
>     // execute tests using n number of browsers running in parallel
>     // shardTestFiles: true,
>     // maxInstances: 2
>   },
> 
>   onPrepare: () => {
>     require('ts-node/register');
>     require('tsconfig-paths/register');
>     browser.ignoreSynchronization = true;
>     browser.waitForAngularEnabled(false);
>   }
> 
>   // restartBrowserBetweenTests: true
> };
> ```

@jan-molak : can you help here please :)

**Comment by abhinaba1080** [comment]
Hi Jan,

Can you please look into the issue. I am totally stuck for the same. I know
, you are busy with quite a lot of work. Sorry for disturbing you.

I just love Serenity Js. And i want my organization also loves the
potential serenity-js provides.

Again sorry for any disturbance I made.

**Comment by jan-molak** [comment]
Hey @abhinaba1080 would you be able to create a sample repo on Github that demonstrates the problem so that I can try to reproduce it? Thanks.

**Comment by abhinaba1080** [comment]
Hi @jan-molak , here it is : https://github.com/abhinaba1080/Protractor-Serenity-Cucumber-BDD-BoilerPlate

**Comment by jan-molak** [comment]
@abhinaba1080 - apologies, when I suggested to use the `Photographer.whoWill(TakePhotosOfInteractions)` factory method I've committed the feature but haven't pushed the code 🤦‍♂ Sorry, schoolboy error.

It's available in the latest alpha (`2.0.1-alpha.77`). Please have a look and let me know what you think!

**Comment by jan-molak** [comment]
Also, the warnings you mention will only show up for the `alpha` versions. That's because `@serenity-js/*` modules have a `2.x` [peer dependency](https://nodejs.org/es/blog/npm/peer-dependencies/) on other `@serenity-js/*` modules, and `2.x-alpha` doesn't meet the `2.x` requirement. It's only temporary and will go away when a "proper" release is out.

```
npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/core@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/cucumber@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/jasmine@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @serenity-js/protractor@2.0.1-alpha.76 requires a peer of @serenity-js/mocha@2.x but none is installed. You must install peer dependencies yourself.

```

**Comment by Cariffo** [comment]
Hello sir,

First of all thank you for your work!

For some time now i have been trying to add screenshots to my serenity-js reports with no success.
I have followed steps written in this issue.

My protractor.conf.js is as:

```
const { Photographer, TakePhotosOfInteractions } = require('@serenity-js/protractor');

serenity: {
    dialect: 'cucumber',
    crew: [
        ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
        new SerenityBDDReporter(),
        new ConsoleReporter(),
        Photographer.whoWill(TakePhotosOfInteractions),
    ]
},
```
My steps run without any errors or issues and the final report does not have needed screenshots.

I have spent some time digging through the documentation and cant wrap my head around the actors. At this moment the project I am working on has none:

for example some feature steps:

```
Feature: Categories
As regular user 
I want to use dance

Scenario: test
    When on Party, user clicks on "Dance" item
```
and implementation:

```
When(/^on Party, user clicks on "([^"]*)" item$/, async (value) => {  
  var el = element(by.id( -- some ID goes here -- ));    
  await el.click();  
});
```
As you can see there are no actors in my project and I would like to avoid having to change implementation as it is a rather big project. The need is to have a screenshot in the report for every single step of every scenario.
Is there some part I am missing? Is it possible?

Thank you for your time and I apologize if this is a rather off-topic question.

**Comment by magdalenaBartkowiakJowsa** [comment]
@Cariffo is it a great question, I have the same problem, reports are generated but without screenshots. @jan-molak would you be so kind to explain us if it is possible to get reports with screenshots attached without implementing Screenplay Pattern?

**Comment by abhinaba1080** [comment]
@magdalenaBartkowiakJowsa ,

what's the serenity-js version you are using? Are you using protractor as your test runner or any other tool?

**Comment by jan-molak** [comment]
Hey @Cariffo, @magdalenaBartkowiakJowsa and @abhinaba1080 - I've raised #362 to remember to add this functionality. I've also suggested a workaround that you can use until that's done.
