### ISSUE TITLE
Integration of serenity report with cucumber

### ISSUE THREAD

**Issue by Bharan5484** [jan-molak/serenity-js#347]
Hi https://github.com/jan-molak,
In my project, they requested to use cucumber framework with typescript using protractor. Along with that they need serenity report alone. is it possible? I have done multiple researches but i didnt get a fine solution. could you please help me on the same. Thanks in advance

**Comment by jan-molak** [comment]
Hi @Bharan5484, sure, have a look at [this example project](https://github.com/jan-molak/serenity-js/tree/2.0/examples/protractor-cucumber).
