### ISSUE TITLE
Issues while migrating to Serenity 2.0

### ISSUE THREAD

**Issue by akshayadesh** [jan-molak/serenity-js#349]
Hi,
We have been using serenity1.0 for some time. But now, as we try to migrate to serenity2.0, we tried to execute the project at https://github.com/jan-molak/serenity-js/tree/2.0/examples/protractor-cucumber. However, the node modules are getting partially installed and during execution we are being thrown the following errors:
```
Errors:
[test:update-serenity] > serenity-bdd update --ignoreSSL
[test:update-serenity]
[test:update-serenity] I'm terribly sorry, but something didn't go according to plan.
[test:update-serenity] Cannot read property 'to' of undefined
[failsafe] Script 'test:update-serenity' exited with code 0
----------------------------------------------------------------------------------------------------
[test:report] > serenity-bdd run
[test:report]
[test:report] I'm terribly sorry, but something didn't go according to plan.
[test:report] I couldn't access the Serenity BDD CLI at node_modules/@serenity-js/cache/serenity-cli-2.1.9-all.jar. Did you remember to run `serenity-bdd update`?
[failsafe] Script 'test:report' exited with code 0
```

Can we have the dependencies required for cucumber-protractor projects? @jan-molak  @serenity-js/cucumber

**Comment by jan-molak** [comment]
Hi @akshayadesh,

Could you please elaborate a bit more on what you mean by `node modules are getting partially installed`? The error you're seeing is most likely related to the dependencies not being available at runtime.

Since the repo you have cloned is a mono-repo, it means that it contains both the Serenity/JS source code as well as the examples.

Basically, you can run the examples in 2 ways:

## Nice'n'easy

This approach is great if you want to simply run the examples using the latest version of Serenity/JS as published to npmjs.com and avoid having to compile the framework itself (most cases):

```
git clone https://github.com/jan-molak/serenity-js.git
cd serenity-js
git checkout 2.0
cd examples/protractor-cucumber
npm install
npm test
```

## Advanced

This approach should be used if you're planning to contribute changes to Serenity/JS itself and would like to check if the changes you've made to Serenity/JS still work with the examples. With this approach you'd be using `make clean verify` which recompiles and tests the Serenity/JS itself.

```
git clone https://github.com/jan-molak/serenity-js.git
cd serenity-js
git checkout 2.0
npm install
make clean verify
cd examples/protractor-cucumber
npm test
```

Let me know if this helps,

Jan

**Comment by akshayadesh** [comment]
Hi Jan!
Your answer helped we could execute the example project. Now we're trying to create our own project with the help of example that you provided. However, we're facing following issues:

1. Serenity JS1.0 used to show structure of unimplemented steps, with serenity-Js 2.0 we are not getting that. It just shows :
 **ImplementationPendingError: Step not implemented
    at CucumberEventProtocolAdapter.outcomeFrom (C:\ui-automation\serenity-example\node_modules\@serenity-js\cucumber\src\listeners\CucumberEventProtocolAdapter.ts:168:54)
    at EventEmitter.<anonymous> (C:\ui-automation\serenity-example\node_modules\@serenity-js\cucumber\src\listeners\CucumberEventProtocolAdapter.ts:140:54)
    at EventEmitter.emit (events.js:187:15)**

2. We are experiencing timeout issues during executions.
For more clarity kindly check the sample repository that we have created: https://github.com/rajeshwarp/serenity-js-example

3. Please help us with the basic assertions. We want to use targets instead of elements. But assertions demand elementFinder for operations like text equals, element present etc. What is the way out to this?

 Thanks,
Akshaya

**Comment by akshayadesh** [comment]
Hello @jan-molak !
Your answer has helped! There is another issue that we are stuck up with.
The protractor.conf.js uses cucumberOptions like this:

 ```
cucumberOpts: {    
    require: [
      "features/step_definitions/*/**.ts",
      "core/common-util/hooks.ts",
      "core/persona.ts",
      "core/stage.ts",
    ],
    format: 'pretty',               // enable console output
    compiler: 'ts:ts-node/register'   // interpret step definitions as TypeScript
  },
```
On execution, we learn that it is unable to find the location for step_definition files. The error reads:

```
[test:acceptance] [16:27:53] E/launcher - Error: Error: ENOENT: no such file or directory, lstat 'C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\features\step_definitions\*'
[test:acceptance]     at Object.realpathSync (fs.js:1454:7)
[test:acceptance]     at Object.expandPathWithExtensions (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\cli\path_expander.js:14:23)
[test:acceptance]     at C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\cli\path_expander.js:8:27
[test:acceptance]     at Array.map (<anonymous>)
[test:acceptance]     at Object.expandPathsWithExtensions (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\cli\path_expander.js:7:31)
[test:acceptance]     at Object.expandPaths (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\cli\support_code_path_expander.js:6:38)
[test:acceptance]     at getSupportCodePaths (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\cli\configuration.js:73:49)
[test:acceptance]     at Object.getSupportCodeLibrary (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\cli\configuration.js:125:30)
[test:acceptance]     at Object.getSupportCodeLibrary (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\runtime.js:44:46)
[test:acceptance]     at Object.start (C:\gitrepo\WebFX\Lifecare-Foundation-TestFx-SerenityJS-Starter-Kit\node_modules\cucumber\lib\cucumber\runtime.js:12:37)
[test:acceptance] [16:27:53] E/launcher - Process exited with error code 100
[test:acceptance] npm ERR! code ELIFECYCLE
[test:acceptance] npm ERR! errno 100
[test:acceptance] npm ERR! lifecare-serenityjs-starter-kit@1.0.0 test:acceptance: `protractor ./protractor.conf.js`
[test:acceptance] npm ERR! Exit status 100
[test:acceptance] npm ERR!
[test:acceptance] npm ERR! Failed at the lifecare-serenityjs-starter-kit@1.0.0 test:acceptance script.
[test:acceptance] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Could you please help us with this?

Thanks,
Akshaya
