### ISSUE TITLE
Not referring the step defintion file

### ISSUE THREAD

**Issue by Bharan5484** [jan-molak/serenity-js#352]
Hi @jan-molak,

I am using cucumber with serenityjs with typescript. Initially am using the folder structure as you mentioned in your site. Later due to project requirement i have changed the folder structure but the feature file not matching the step defintion file. I am also attaching the screenshot herewith for your reference. Kindly assist me ASAP as i have short deadline
![image](https://user-images.githubusercontent.com/51324530/66500116-a3027f80-eade-11e9-80f5-b8bfa70414e4.png)

**Comment by Bharan5484** [comment]
tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by rajeshwarp** [comment]
Hello, please check #350. It might help

**Comment by jan-molak** [comment]
Hi @Bharan5484,

Based on your screenshot it seems like on line `34` you're trying to require TypeScript files from `./e2e/src/features/**/*.ts`, but the project structure shows that there's no such directory (it would need to be relative to the `protractor.conf.js`).

Perhaps you meant to refer to `./src/features/**/*.ts` instead?
