### ISSUE TITLE
Need Performance Analyser with Serenity Js

### ISSUE THREAD

**Issue by abhinaba1080** [jan-molak/serenity-js#353]
Hi Jan,

There are couple of client side performance analysis tools available in market such as Lighthouse and sitespeed.io etc. Sadly, they have no Integration with protractor/ cucumber. 

So, do you plan to integrate an performance analyser for serenity cucumber scenarios? Let us know if something similar is already available.

**Comment by abhinaba1080** [comment]
I integrated lighthouse with protractor with the help of yhe remote debugging port. Closing the issue.

**Comment by jan-molak** [comment]
This sounds cool! Did you happen to document the way you've done it somewhere so that we can all learn from your experience?

**Comment by abhinaba1080** [comment]
Hi,

I have written a Medium blog on this:

https://medium.com/@abhinabaghosh.1994/measure-your-websites-performance-with-google-lighthouse-and-protractor-1a6086267800

This basically with native jasmine, but can be easily integrated with Serenity as well.

Repo is here: https://github.com/abhinaba1080/protractor-lighthouse-integration
