### ISSUE TITLE
Suggestion required: Restricting Abilities based on Persona

### ISSUE THREAD

**Issue by rajeshwarp** [jan-molak/serenity-js#360]
Hi @jan-molak ,
We have started using SerenityJs 2.0 in our Projects. We have figured out personas to be used by teams for our Workflow testing.  We do not want everyone to create his or her own personas, instead use from the list defined by  stakeholders.

We currently implemented  this by creating a core package with Personas and their abilities and plan is to create a package and publish so that every team is using defined set of personas and abilities.

**--  Our Current Thought Process  -- 
core/persona.ts**
```
/**
 * List of Personas that can be used in framework
 */
export enum Persona {
  ABC,
  /**
   * ABC:  a Patient
   */
  XYZ,

  /**
   * XYZ: Is an Doctor
   */
  MNO,
  /**
 * MNO: Is an Nurse
 */
}
```
**Preparing Actor with abilities** 
_**core/customestage.ts**_
```
export class customStage implements DressingRoom {
      
    prepare(actor: Actor): Actor {
      
        switch (actor.name) {

            case 'ABC':
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser));

            case 'MNO':
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser));
                  
            case 'XYZ':
              
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser),
                    Search.with("ourapplication", ''));//custom ability 

            
            default:
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser),);
        }
    }
}
```

**_core/setup.ts_**
```
export function customactor(persona: string): Actor {
    return serenity.callToStageFor(new customStage()).theActorCalled(persona)
  }
setWorldConstructor(customactor)
```
**_stepdefination.ts_**

```
let xyz = customactor(Persona[Persona.XYZ])

Given(/^that XYZ is an authorized user of our system$/,  async ()=>  {
    return xyz.attemptsTo(Be.onOurSystem())
  });

```
Need your inputs on if this is the correct approach. With above implementation, we lose flexibility to reuse step_definition as we are preparing actor and providing them with the abilities based on the names in persona enum. But can enforce that no one creating their own random personas/abilities across organization.

If we go with the feature file and step_definition shown in your example, It can work for any actor. Wondering how we can handle the restrictions we want to impose in similar way. Also we wanted to keep step definition precise   ` return xyz.attemptsTo(Be.onOurSystem())`
```
Given(/(.*) decides to use the Super Calculator/, function (this: WithStage, actorName: string) {
    return this.stage.theActorCalled(actorName).attemptsTo(
        Navigate.to('/protractor-demo/'),
    );
});
```

Thank You for all your great work and help!

**Comment by jan-molak** [comment]
Hi @rajeshwarp 

> We have started using SerenityJs 2.0 in our Projects. We have figured out personas to be used by teams for our Workflow testing. We do not want everyone to create his or her own personas, instead use from the list defined by stakeholders.

Sure, sounds like a good idea. This approach is particularly useful when you have a UX team or simply want to share the personas cross-team.

> Preparing Actor with abilities core/customestage.ts

Your implementation looks good, and you could simplify it further if the actors have the same abilities, but different names:

```typescript
export class Actors implements DressingRoom {
      
    prepare(actor: Actor): Actor {
      
        switch (actor.name) {

            case 'ABC':             // a fall-through case statement
            case 'MNO':
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser));

            case 'XYZ':
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser),
                    Search.with("ourapplication", ''));  //custom ability 
           
            default:
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser),);
        }
    }
}
```

You could also throw an error if you really wanted to actively highlight that people should only ever use the predefined personas:

```typescript
import { RuntimeError } from '@serenity-js/core';

export class InvalidPersonaError extends RuntimeError {

    /**
     * @param {string} message - Human-readable description of the error
     * @param {Error} [cause] - The root cause of this {@link RuntimeError}, if any
     */
    constructor(message: string, cause?: Error) {
        super(InvalidPersonaError, message, cause);
    }
}
```

and then in your `Actors` class:

```typescript
export class Actors implements DressingRoom {
      
    prepare(actor: Actor): Actor {
      
        switch (actor.name) {

            case 'ABC':
            case 'MNO':
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser));

            case 'XYZ':
                return Actor.named(actor.name).whoCan(
                    BrowseTheWeb.using(protractor.browser),
                    Search.with("ourapplication", ''));  //custom ability 
           
            default:
                throw new InvalidPersonaError(`The actor called ${ actor.name } is not one of the recognised personas. Please read <link to a wiki or some docs explaining your design choice>`)
        }
    }
}
```

## core/setup.ts

I wouldn't necessarily recommend using the below setup function, simply because it's not really leveraging the Cucumber World concept

```typescript
export function customactor(persona: string): Actor {
    return serenity.callToStageFor(new customStage()).theActorCalled(persona)
 }
setWorldConstructor(customactor)
```

Consider the below construct instead:

```typescript
import { serenity, WithStage } from '@serenity-js/core';
import { setWorldConstructor } from 'cucumber';
import { Actors } from './path/to/my/custom/Actors';

setWorldConstructor(function (this: WithStage, { parameters }) {
    this.stage = serenity.callToStageFor(new Actors());
});
```
This gives you access to the `stage` object on every step definition and ensures that the actors are instantiated when they're needed (i.e. should you want to restart the browser between tests).

```typescript
Given(/^(.*) has started working with a patient (.*)$/,  function(this: WithStage, actorName: string, patientName: string) {
    return this.stage.theActorCalled(actorName).attemptsTo(
        StartWorkingWithAPatient.called(patientName),
    )
});
```

Also, please note that you don't need the `async` keyword and that you should define the step body using the `function` keyword rather than the arrow function ([learn more](https://github.com/cucumber/cucumber-js/blob/master/docs/faq.md))

## Step def reuse

I wouldn't necessarily worry too much about trying to reuse the step definitions as they should be a thin and simple glue layer between the Gherkin and your test automation code (Serenity/JS). Check out [Aslak Hellesøy's thoughts on this matter](https://aslakhellesoy.com/post/11055981222/the-training-wheels-came-off).

You can quite easily create high-level `Task`s, like "StartWorkingWithAPatient", "AuthenticateWithTheHealthareApp", etc., package them up together with your custom `Actors` and `Abilities` and share across the teams.

---

I'm not sure what you mean by:
> If we go with the feature file and step_definition shown in your example, It can work for any actor. Wondering how we can handle the restrictions we want to impose in a similar way. Also we wanted to keep step definition precise return xyz.attemptsTo(Be.onOurSystem())

Could you please elaborate on it some more?

**Comment by rajeshwarp** [comment]
Hi @jan-molak ,
Thanks for the suggestions and guidance,  I tried above approach however **setWorldConstructor** is not getting called and on execution getting 

>  TypeError: Cannot read property 'theActorCalled' of undefined


```
import { serenity, WithStage } from '@serenity-js/core';
import { setWorldConstructor, setDefaultTimeout } from 'cucumber';
import { Actors } from '../core/stage';

setWorldConstructor(function (this: WithStage, { parameters }) {
   console.log("**********************I am called")
    this.stage = serenity.callToStageFor(new Actors());
});

```
Error: 
```

 [test:execute] TypeError: Cannot read property 'theActorCalled' of undefined
[test:execute]     at World.<anonymous> (C:\Users\patilraj\Desktop\work\serenity\step_definitions\application\search_steps.ts:13:19)
```
StepDefination:
```

Given(/that (.*) is an authorized user of the system/, function (this: WithStage, actorName: string,name:string, pass:string) { 
return this.stage.theActorCalled(actorName).attemptsTo(
 Login.toTheApplication(name, pass)
)
});
```

Seems like I am missing something.

**Comment by rajeshwarp** [comment]
Got it working ! my bad ,  was missing file path in config. Thank You!
