### ISSUE TITLE
Rerun of failed Scenarios

### ISSUE THREAD

**Issue by AbhineetSharmax** [jan-molak/serenity-js#371]
Hi @jan-molak , 

Thank you for all the hardwork.

Is there any option with which we may re run the failed scenarios? Please suggest.

Thanks,
Abhineet Sharma

**Comment by abhinaba1080** [comment]
This will help you :https://github.com/jan-molak/serenity-js/issues/101

**Comment by jan-molak** [comment]
Thanks @abhinaba1080 - closing as a duplicate of #101
