### ISSUE TITLE
serenity-js " unable to require .d.ts"

### ISSUE THREAD

**Issue by NiyiFalade** [jan-molak/serenity-js#378]
Hello Folks ... I am playing arround serenity js screenplay but get this error message 

[09:34:05] I/launcher - Running 1 instances of WebDriver
[09:34:05] I/direct - Using ChromeDriver directly...
Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `World.d.ts`.
[09:34:08] I/launcher - 0 instance(s) of WebDriver still running
[09:34:08] I/launcher - chrome #01 failed 1 test(s)
[09:34:08] I/launcher - overall: 1 failed spec(s)
[09:34:08] E/launcher - Process exited with error code 1

my package.json
{
  "name": "cm_js_test",
  "version": "0.0.1",
  "description": "content manager javascript test framework ",
  "main": "index.js",
  "scripts": {
    "e2e-tag": "protractor ./protractor.conf.js --cucumberOpts.tags",
    "webdriver-update": "webdriver-manager update --versions.chrome=72.0.3626.69",
    "report": "serenity run",
    "test": "failsafe e2e report",
    "clean": "rimraf target",
    "pretest": "serenity update"
  },
  "keywords": [
    "content",
    "manager",
    "javascript",
    "test",
    "framework"
  ],
  "license": "ISC",
  "peerDependencies": {},
  "devDependencies": {
    "@types/chai": "3.4.34",
    "@types/chai-as-promised": "0.0.29",
    "@types/node": "^6.0.53",
    "chai": "3.5.0",
    "chai-as-promised": "5.3.0",
    "chai-smoothie": "^0.2.0",
    "cucumber": "^1.3.2",
    "npm-failsafe": "^0.4.1",
    "protractor": "^5.1.1",
    "rimraf": "2.5.4",
    "serenity-cli": "0.x",
    "serenity-js": "^1.10.13",
    "ts-node": "^1.7.2",
    "tslint": "4.3.1",
    "typescript": "^2.1.4"
  }
}

**Comment by Ijee** [comment]
Your dependencies are pretty outdated in general. But from a quick search it looks like it is related to the ts-node dependency.

**Comment by jan-molak** [comment]
I agree with @Ijee's assessment - @NiyiFalade could you please try to update your dependencies and let us know if this helps to resolve the issue you're seeing?

I'll close the ticket for now, but please feel free to reopen it if the proposed approach doesn't work.
