### ISSUE TITLE
Console Reporter not found

### ISSUE THREAD

**Issue by rajeshwarp** [jan-molak/serenity-js#380]
Hi Jan,

Greetings,

While running Tests today , I am getting following error , Is something changed wrt ConsoleReporter: 
`[test:execute] [11:35:44] E/configParser - Error code: 105
[test:execute] [11:35:44] E/configParser - Error message: failed loading configuration file ./protractor.conf.js
[test:execute] [11:35:44] E/configParser - TypeError: ConsoleReporter is not a constructor`

Config file looks like this:

```
const
  { ArtifactArchiver,ConsoleReporter} = require('@serenity-js/core'),
  { SerenityBDDReporter } = require('@serenity-js/serenity-bdd'),
  { Photographer, TakePhotosOfInteractions } = require('@serenity-js/protractor');


module.exports = {
  chromeDriver: require(`chromedriver/lib/chromedriver`).path,
  framework: 'custom',
  frameworkPath: require.resolve('@serenity-js/protractor/adapter'),
  SELENIUM_PROMISE_MANAGER: false,
  allScriptsTimeout: 11000,
  directConnect: true,

  serenity: {
    runner: 'cucumber',
    crew: [
      ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
      Photographer.whoWill(TakePhotosOfInteractions),     // or Photographer.whoWill(TakePhotosOfFailures),
      new SerenityBDDReporter(),
      new ConsoleReporter(process.stdout, process.stderr)
    ]
  },
```

**Comment by jan-molak** [comment]
Hi @rajeshwarp - I wrote a new version of the console reporter, it's available as `@serenity-js/console-reporter` - https://www.npmjs.com/package/@serenity-js/console-reporter

**Comment by rajeshwarp** [comment]
Thanks, Jan will try out this.

Regards!

**Comment by jan-molak** [comment]
Cool, thanks! Check out [this comment](https://github.com/jan-molak/serenity-js/issues/318#issuecomment-557953258) to see what the new reporter is capable of.
