### ISSUE TITLE
Serenity report links to the same result

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#39]
Hello! I have an issue dealing with serenity report when I use a scenario outline. Given I have this feature content:
    
    Scenario Outline: View items added in cart
    Given I am in the Cart page
    When I view the items in cart
    Then I expect to see the added title of <Title>, with unit price of <Unit Price>, quantity of <Quantity> and total price of <Total>
    
    Examples:
    |Title                                        |Unit Price|Quantity|Total    |
    |The Singular Universe and the Reality of Time|£19.99    |1       |£19.99   |
    |The Reader's Brain                           |£12.99    |1       |£12.99   |

But in my serenity report, the links are only referring the same report page only after you click and it only displays the last test data executed on the report. Refer to screenshots below for clarity. Cheers!

URL links:
![url links](https://cloud.githubusercontent.com/assets/13494822/25794488/b68a8d48-3403-11e7-80c4-5e47d27385df.png)

Scenario durations:
![scenario durations](https://cloud.githubusercontent.com/assets/13494822/25794619/54fcad1c-3404-11e7-9ae4-3a7c784c7d31.png)

Last scenario execution only displayed:
![last scenario execution only displayed](https://cloud.githubusercontent.com/assets/13494822/25794496/bef825a8-3403-11e7-9932-ec933bb60f18.png)

**Comment by jan-molak** [comment]
Hey, @marktigno! There's a difference between CucumberJVM and Cucumber.js where the former notifies its listeners of the fact that a given `Scenario` is, in fact, a `Scenario Outline`, and the latter doesn't. 

What this means is that from the point of view Serenity/JS, both examples refer to the same scenario.

However, what you can do is to add the name of the example to the scenario title, for example:

```gherkin
Scenario Outline: View items added in cart - <Title>       # <-- I've added <Title> here

Given I am in the Cart page
 When I view the items in cart
 Then I expect to see the added title of <Title>, with unit price of <Unit Price>, quantity of <Quantity> and total price of <Total>

Examples:
|Title                                        |Unit Price|Quantity|Total    |
|The Singular Universe and the Reality of Time|£19.99    |1       |£19.99   |
|The Reader's Brain                           |£12.99    |1       |£12.99   |
```

Does this help?
Jan

**Comment by marktigno** [comment]
Hello @jan-molak! Thanks for the tips, now it looks good on the reports. Cheers!

**Comment by jan-molak** [comment]
Sweet! Thanks for letting me know :-)
