### ISSUE TITLE
Cucumber expressions are not recognised in step definitions

### ISSUE THREAD

**Issue by testifyqa** [jan-molak/serenity-js#414]
If I have a step definition like so...
```
Given(/that (.*) wants to eat out at a recommended restaurant/, (actorName: string) => {
    console.log('i want food');
});
```
this works fine as `(.*)` is RegEx.

If I instead use a Cucumber expression in the step definition like so...
```
Given(/that {string} wants to eat out at a recommended restaurant/, (actorName: string) => {
     console.log('i like pizza');
});
```

the step is not found and is shown as pending still.

Additionally, my steps only work when I replace the single quotes with '/'

**Comment by testifyqa** [comment]
using cucumber v6.0.5

**Comment by jan-molak** [comment]
Hi @testifyqa - as far as I'm aware this is by design since Cucumber expressions are only supported in `string`, but not in `RegEx`. I've been playing with them recently so you might find [this little demo](https://github.com/serenity-js/todomvc-demo/blob/65fbbebb69fdda672a2d48b7ab799d59afd644d8/features/step_definitions/todomvc.steps.ts) useful in your research. 

So while the below would be interpreted as a Cucumber expression:
```
Given('that {string} wants to eat out at a recommended restaurant', () => {})
```
this one would be interpreted as RegEx instead:
```
Given(/that {string} wants to eat out at a recommended restaurant/, () => {})
```

Does this help?

Jan

**Comment by testifyqa** [comment]
Hi Jan, I believe I tried using a cucumber expression with single quotes (just retried it too) as below but i still got the error saying it is pending...

```
import { Given, When, Then } from "cucumber";
import { browser } from "protractor";

Given('that {string} wants to eat out at a recommended restaurant', (actorName: string) => {
    browser.get('https://www.zagat.com');
});
```

**Comment by testifyqa** [comment]
Just slightly edited the step to match the little demo you linked me to but I still get the same result :(

```
Given('that {string} wants to eat out at a recommended restaurant', (actorName: string) => 
    browser.get('https://www.zagat.com'),
);
```

**Comment by jan-molak** [comment]
Interesting, I don't think it's Serenity/JS related, but maybe I could help you out.

What are the contents of your feature file? Maybe it's just some typo somewhere that prevents Cucumber from finding the step def?

**Comment by testifyqa** [comment]
Thanks,

Feature file name: `find_a_restaurant.feature`

Feature file contents:
```
Feature: Find a restaurant
 
  As Frank (a lover of food)
  I want to find recommended restaurants to eat in
  So that I can feed my appetite with great cuisine
 
  Scenario: Searching for all restaurants in San Diego
    Given that Frank decides to use Zagat to find recommended restaurants
    When he searches for all restaurants in his area of San Diego
    Then a list of recommended restaurants in San Diego are returned to him
```

Step Defs name: `foodie.steps.ts`

Current Step Defs content:
```
import { Given, When, Then } from "cucumber";
import { Navigate } from '@serenity-js/protractor';
import { WithStage } from '@serenity-js/core';

Given(/that (.*) decides to use Zagat to find recommended restaurants/, function(this: WithStage, actorName: string) {
    return this.stage.theActorCalled(actorName).attemptsTo(
        Navigate.to('/national'),
    );
});

When(/(?:he|she) searches for all restaurants in (?:his|her) area of (.*)/, (location: string) => {
    // Write code here that turns the phrase above into concrete actions
    return 'pending';
});

Then(/a list of recommended restaurants in (.*) are returned to (?:him|her)/, (location: string) => {
    // Write code here that turns the phrase above into concrete actions
    return 'pending';
});
```

**Comment by testifyqa** [comment]
Currently the given step works fine as above when i run `npm test`

**Comment by jan-molak** [comment]
OK, this makes sense. Check out [Cucumber docs](https://cucumber.io/docs/cucumber/cucumber-expressions/):

```
{int} - Matches integers, for example 71 or -19.
{float} - Matches floats, for example 3.6, .8 or -9.2.
{word} - Matches words without whitespace, for example banana (but not banana split)
{string} - Matches single-quoted or double-quoted strings, for example "banana split" or 'banana split' (but not banana split). Only the text between the quotes will be extracted. The quotes themselves are discarded. Empty pairs of quotes are valid and will be matched and passed to step code as empty strings.
{} - anonymous | Matches anything (/.*/).
```

What if you try `{word}` instead?

**Comment by testifyqa** [comment]
Ah I see. Thanks so much for digging in to this and explaining. I’ve only really used RegEx and not Cucumber expressions but will add the quotes in or {word) and see how that goes :) cheers

**Comment by testifyqa** [comment]
This works as described by you and the docs, closing off :D
