### ISSUE TITLE
Serenity report - The report doesn't contain all the examples provided for the Scenario Outline

### ISSUE THREAD

**Issue by rakeshnambiar** [jan-molak/serenity-js#421]
The report doesn't contain all the examples provided for the Scenario Outline. It's just showing the last example data in the report. Due to this, in case the test is failed for any other data, still, the report says 100% PASS for multiple browsers (in case the tests are running on multiple browsers).

`How to reproduce it:`
Run the test for a single feature and the feature must contain a single scenario outline with multiple data in the example section.

`Run command user:`
npm install-test

**Comment by jan-molak** [comment]
Hi @rakeshnambiar and thanks for the report!

Am I assuming correctly that you're using version 1.x of Serenity/JS? If that's the case then you've probably encountered #39 (there's a workaround proposed in that ticket too).

Serenity/JS v2 comes with a new implementation of the Cucumber adapter, which supports scenario outlines without any workarounds. Check out the [template repo](https://github.com/serenity-js/serenity-js-cucumber-protractor-template).

Does this help?

**Comment by rakeshnambiar** [comment]
@jan-molak yes - you are right. I am still on version 1.x. I will check #39

**Comment by jan-molak** [comment]
I'll close this ticket for now; please feel free to re-open it if the workaround doesn't help or you find a similar issue in 2.x

**Comment by rakeshnambiar** [comment]
Thanks @jan-molak it's now worked through the way you recommended on the ticket #39 . I will try the latest version and update you in case the issue still exists.

**Comment by jan-molak** [comment]
Brilliant, thanks for letting me know, @rakeshnambiar!

**Comment by rakeshnambiar** [comment]
@jan-molak another question on the same context. Is it possible to use the new report with version 1.x ? Because I have already some test suites developed in version 1 using JavaScript without screenplay.
