### ISSUE TITLE
failing tests not appearing in serenity html report

### ISSUE THREAD

**Issue by nbarrett** [jan-molak/serenity-js#43]
I might have done something completely wrong in my mocha-based serenity project but when I run the suite end to end using `npm test`, I see the following errors in the console:

![image](https://cloud.githubusercontent.com/assets/626941/26373103/350a5df6-3ff8-11e7-9f56-80da0988936c.png)

But when I look at the serenity report, I don't see those failing tests at all. 
If you want some context, I have [a commit here in my personal project](https://github.com/nbarrett/ekwg/commit/a742e93ebe684b199548ac5e9217a8af4dfbcb2b) as an example.

I would expect all tests regardless of outcome to be represented in the final serenity report wouldn't I?

**Comment by jan-molak** [comment]
Yes, they should; I'll need to check this.

In the meantime, you can increase the timeout of a specific mocha test [as follows](https://stackoverflow.com/questions/15971167/how-to-increase-timeout-for-a-single-test-case-in-mocha).

**Comment by nbarrett** [comment]
Cool thanks Jan. I added `` to the test cases that were causing timing problems (not sure why 
```
allScriptsTimeout: 11000,
getPageTimeout: 11000,
```
didn't work), but this didn't fix the second failure onwards as this was caused by:
```
NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
``` 

So I hacked the following protractor config 
`restartBrowserBetweenTests: false` property and that problem went away. But maybe there is a browser lifecycle problem lurking here?

**Comment by jan-molak** [comment]
Could be; The browser lifecycle control falls under Protractor's remit though. Check out @ttretau [comment](https://github.com/jan-molak/serenity-js/issues/34#issuecomment-302450112)

**Comment by nbarrett** [comment]
So is your conclusion @jan-molak / @ttretau that `restartBrowserBetweenTests: true` is to be avoided?

**Comment by jan-molak** [comment]
So that's the thing; I'd personally always start with a clean and fresh environment to run my test in, and this includes a browser, but I'm not sure how stable that is in Protractor :/ I guess some further analysis/debugging is needed.

**Comment by nbarrett** [comment]
My personal experience is that there is a lot of overhead (aka: elapsed time/moving parts/risk of memory leaks) in creating a new browser, so prefer not to actually. As long as we have clean session/non residual cookies then this is good enough?

**Comment by ttretau** [comment]
My experience - in my cucumber based project - is that two short unneeded sessions are started after the actual session. But this has no impact on my local testing or with a private selenium grid. Only on browserstack this is leading to empty sessions at the browserstack reporting..

**Comment by jan-molak** [comment]
@nbarrett, @ttretau - the issue seems to be related to how Protractor handles browser restarts. I've created a new ticket so that the conversation is easier to find for people who might encounter this problem - #56
