### ISSUE TITLE
Make huge example

### ISSUE THREAD

**Issue by tamascsaba** [jan-molak/serenity-js#49]
Hi,

I haven't found any large example in github yet. Only this project use serenity-js
- https://github.com/jan-molak/serenity-js-example
https://github.com/jan-molak/serenity-js-fast-track-demo
- https://github.com/serenity-js/tutorial-journey-planner
- https://github.com/serenity-js/tutorial-cross-app-testing
- https://github.com/serenity-js/tutorial-from-scripts-to-serenity

I want to see, how handle serenity (and screenplay pattern) this subject in a large example.
- authentication/authorization
- basic pages (user settings, blog etc..)
- advanced pages (search, wizzard)
- multiple environments (rest resources)
- component test like datepicker, dropdown, datable, forms etc..

**Comment by jan-molak** [comment]
Hey @tamascsaba!

The basic building blocks [are demonstrated here](https://github.com/jan-molak/serenity-js/tree/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/spec/cookbook), and you should be able to use them to assemble more complex tasks.

I agree that some more advanced examples would be useful though. I'll be adding them to the [serenity-js.org](http://serenity-js.org) website, and if you come up with your own examples I'd be more than happy to include them in the [community section](http://serenity-js.org/community.html).

**Comment by jan-molak** [comment]
I've just created two seed projects to help you get started:
- [Serenity/JS Cucumber seed](https://github.com/serenity-js/seed-cucumber)
- [Mocha seed](https://github.com/serenity-js/seed-mocha)

More examples to follow!

**Comment by tamascsaba** [comment]
:+1: :)

**Comment by malindapw** [comment]
@jan-molak  , I tried that Serenity/JS Cucumber seed project. I am new to Protractor. Please want to know why it's does not open the browser when it's running? thanks
