### ISSUE TITLE
Cannot read property 'indexOf' of undefined -  within actor.ts

### ISSUE THREAD

**Issue by nbarrett** [jan-molak/serenity-js#64]
When I invoke a task in a data-driven way e.g. I get some data from a promise, then call tasks within  then(), the exception `Cannot read property 'indexOf' of undefined at node_modules/serenity-js/src/serenity/screenplay/actor.ts:148:10` is thrown.

Here is an example of the construct I want to be able to use:

```
performAs(actor: PerformsTasks & UsesAbilities): PromiseLike<void> {
        return RamblersWalkSummaries.queryData(actor).then(walks => {
            return actor.attemptsTo(
                ...walks.map(walk =>
                    Click.on(walk.checkboxTarget)));

        });
    }
```

When I simplify the code to some hard-coded values it works e.g.

```
performAs(actor: PerformsTasks & UsesAbilities): PromiseLike<void> {
        const indexValues = [0, 4, 2];
        return actor.attemptsTo(
            ...indexValues.map(rowIndex => Click.on(RamblersTargets.checkboxSelector(rowIndex))))
    };
```

**Comment by nbarrett** [comment]
the code that fails is the first line in actor.ts:

```
// todo: extract
function locateCallerOf(method: string) {
    const origin_of = (frames: StackFrame[]): number => frames.findIndex(frame => !! ~frame.functionName.indexOf(method));
    const get_frame = (frames: StackFrame[]): StackFrame => frames[origin_of(frames) + 1];
    const frames_of_interest = (frame: StackFrame) => !~ frame.fileName.indexOf('node_modules');
    const to_location = (frame: StackFrame): SourceLocation => ({
        path:   frame.fileName,
        line:   frame.lineNumber,
        column: frame.columnNumber,
    });

    return StackTrace.get({ filter: frames_of_interest }).then(get_frame).then(to_location);
}
```

**Comment by jan-molak** [comment]
Thanks Nick, would you mind creating a minimum runnable test case that would allow me to reproduce the problem? Ideally, something running against a public website :-)

**Comment by nbarrett** [comment]
Hi @jan-molak! I've forked the [mocha-seed](https://github.com/serenity-js/seed-mocha) project and there is a repo that reproduces #64 [here](https://github.com/nbarrett/serenity-js-issues/commit/df17f62b3929231ae3766c4ec66e6ca2b5e1b6b2)

**Comment by nbarrett** [comment]
Thanks @jan-molak! Works perfectly with serenity-js 1.7.0 👍
