### ISSUE TITLE
Interacting with alert windows

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#71]
Hello! Is there a way to interact with the browser's alert windows and click either OK or Cancel button on it? The only way that I can do this is to use native protractor command like this:
     
    protractor.browser.switchTo().alert().accept();

Thanks!

**Comment by nbarrett** [comment]
Hi @marktigno - have you seen #65?

**Comment by marktigno** [comment]
Yeah I saw you comments there, but I have a way to work out this using TypeScript version 2.3.4. Here's the working code I did:

    export class DeleteAddress implements Task {
         static click(addressName) {
             return new DeleteAddress(addressName);
        }

        @step('{0} deletes the selected address named #addressName')
        performAs(actor: PerformsTasks): PromiseLike<void> {
            var ptor = protractor.browser;
            return actor.attemptsTo(
                Click.on(ProfilePageComponent.Delete_address_button(this.addressName))
             ), 
            ptor.switchTo().alert().accept();
        }

        constructor(private addressName: string) {}
    }

But this code won't work anymore on the latest version of TypeScript (v2.4.1).

**Comment by jan-molak** [comment]
Not yet, we'll need to create a new interaction for that and extend the `BrowseTheWeb` interface.

I guess we could have a method on `BrowseTheWeb`:

```typescript
class BrowseTheWeb implements Ability {

  alert(): <not sure about the return type?> {
    return this.browser.switchTo().alert();
  }
}
```

And some interactions, like:

```typescript
const AcceptAlert = () => Interaction.where(`#actor accepts the alert`, 
  actor => BrowseTheWeb.as(actor).alert().accept()
)
```

**Comment by marktigno** [comment]
That would be awesome if this is implemented because the are still websites that still uses alert windows. ^_^

**Comment by nbarrett** [comment]
hey @marktigno I've got a PR here 019058f in #65...awaiting some tweaks from the master 😄

**Comment by marktigno** [comment]
Hello @nbarrett! This is pretty good, it got everything what I need for (and everyone else I think). This should be merged right @jan-molak? ^_^V

**Comment by nbarrett** [comment]
Hi @marktigno - just to let you know that I've now completed the PR and have passing tests in 
002b86d. Just waiting for the merge from the serenity master now!

**Comment by marktigno** [comment]
Awesome, I'll check on this once this has been released in the wild. Thanks! ^_^V

**Comment by jan-molak** [comment]
The feature has been merged in and published. Thanks, @nbarrett!

**Comment by habmukandu** [comment]
@jan-molak do you plan to support alert interactons also in serenity-js 2.0?

**Comment by nbarrett** [comment]
Hi @habmukandu - I'm working on a migration guide at the moment which will also include a couple of PRs to cover yet-to-migrate to 2.0 tasks - one of which will be alerts, so stay tuned!
