### ISSUE TITLE
ActiveWait timeout is hardcoded

### ISSUE THREAD

**Issue by iManinesan** [jan-molak/serenity-js#74]
Hi, I've found Wait.until() uses the ActiveWait with default timeout value! how could I increase the timeout?

In serenity-js\src\serenity-protractor\screenplay\interactions\wait.ts
```
export class Wait {
    static for   = (duration: Duration): Interaction => new PassiveWait(duration);
    static upTo  = (timeout: Duration) => new ActiveWait(timeout);
    static until<T>(somethingToWaitFor: T, condition: SuccessCondition<T>) {
        return new ActiveWait().until(somethingToWaitFor, condition);
    }
}

export class ActiveWait {
    private static Default_Timeout = Duration.ofSeconds(5);

    until<T>(somethingToWaitFor: T, condition: SuccessCondition<T>): Activity {
        return condition(somethingToWaitFor, this.timeout);
    }

    constructor(private timeout: Duration = ActiveWait.Default_Timeout) {
    }
}
```

P.S: Deeply appreciate your work, Congrats!

**Comment by jan-molak** [comment]
Hey @iManinesan and thanks for your kind words, I'm glad that you're finding my work helpful :-)

You're right, this should be configurable. Before I get around to making it configurable, though, you could implement your own version of `ActiveWait` and use that instead of the built-in one for now.
