### ISSUE TITLE
Features tab does not include all the web browser tests

### ISSUE THREAD

**Issue by jbprat** [jan-molak/serenity-js#75]
Hello, I configured my Angular project to run Protractor with Cucumber-JS and to get a report with SerenityJS. I am able to run a report but I do not see the features tab.

Here is my folders organization:

```
 - features
 --- features
 ----- foo.feature.ts
 ----- bar.feature.ts
 --- resources // Helpers and json values
 --- steps
 --- tsconfig.e2e.json
```

Here is my protractor configuration:

```
exports.config = {
  allScriptsTimeout: 11000,

  seleniumAddress: 'http://localhost:4444/wd/hub',

  baseUrl: 'http://localhost:4200',

  specs: [
    './features/features/*.ts'
  ],

  multiCapabilities: [{
    'browserName': 'firefox'
  }, {
    'browserName': 'chrome'
  }],

  directConnect: false,

  framework: 'custom',

  frameworkPath: require.resolve('serenity-js'),

  cucumberOpts: {
    require: ['./features/steps/*.ts'],  // require step definition files before executing features
    format: ["pretty"] // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
  },

  beforeLaunch: function() {},

  onPrepare: function () {
    require('ts-node').register({
      project: 'features/tsconfig.e2e.json'
    });
    browser.driver.manage().window().setSize(1800, 1500);
  }
};
```

I am using:
- Angular 4.1.
- Protractor 5.1.
- CucumberJS 1.3.3
- SerenityJS 1.8.0

My report only gives me `Overall test results` and `Requirements ` tabs. Let me know if you need more informations.

**Comment by jan-molak** [comment]
Hey, @jbprat!

Would you be able to push the skeleton project to github so I could try to reproduce the issue?

One thing that makes me think is that your feature files have a `.feature.ts` extension rather than just `.feature`. Is that the case?

J

**Comment by jbprat** [comment]
The feature.ts instead of just feature was the issue.
Now that I have my features and capabilities tabs, I see another issue.

I'm running the tests with IE, Chrome and Firefox, in the report if I click on a feature from the Test count panel, I can see all my different tests:
![feature-page](https://user-images.githubusercontent.com/7212417/28880726-eeb6f1d0-7773-11e7-9a2d-5d695b672532.jpg)

But if I click on the features tab, I can only see one automated test, as you can see here:
![features-page](https://user-images.githubusercontent.com/7212417/28880797-1563ba02-7774-11e7-8c09-83a696999d9c.jpg)

**Comment by jbprat** [comment]
I'll need an hour to create a skeleton of the project, so let me know if you still need it.

**Comment by jan-molak** [comment]
That would be helpful, thanks very much! You might want to use the [cucumber seed](https://github.com/serenity-js/seed-cucumber) to create the skeleton.

**Comment by jbprat** [comment]
Hi, 

I tested the issue with your repository and the bug is pretty easy to reproduce without me having to push a github repository. Here are the steps:
 - Replace the capabilities key in the config with this code:
```
    multiCapabilities: [{
        browserName: 'chrome',

        chromeOptions: {
            args: [
                '--disable-infobars',
                // "--headless",
                // "--disable-gpu",
                // "--window-size=1024x768"
            ]
        }
    }, {
        browserName: 'firefox'
    }]
```

To be able to run Firefox, I used a webdriver-manager globally installed instead of your local one.
I had to add this line to the protractor config:
```
    seleniumAddress: 'http://localhost:4444/wd/hub',
```

You can see the different behaviours below.
![molak-home-page](https://user-images.githubusercontent.com/7212417/29140491-a970f9ea-7d18-11e7-95f5-899564d20c1b.jpg)

![molak-feature-page](https://user-images.githubusercontent.com/7212417/29140496-ac01c96e-7d18-11e7-9e9a-0835bfcc6c47.jpg)

Let me know if you can reproduce the issue!

**Comment by jan-molak** [comment]
@jbprat, does the issue you're facing look similar to the one reported on [StackOverflow here](https://stackoverflow.com/questions/45188063/serenity-js-cucumber-protractor-tabs-capabilities-features-not-visible-in-ht)? I.e. is it due to the location of your `protractor.conf.js`?

**Comment by jbprat** [comment]
Hi,

No, it was my first issue. I'm the commenter on it. Since I renamed my e2e folder to features I can see the tabs, the report is just different as I've shown you in the example.

I'm going to fork your repository to show you the behavior!

Envoyé de ProtonMail mobile

-------- Message d'origine --------

**Comment by jbprat** [comment]
You can checkout my fork from your cucumber-seed project! https://github.com/jbprat/seed-cucumber
I updated the readme with instructions on how to run firefox.

**Comment by jbdealflo** [comment]
@jan-molak Did you get the time to see my repo?

**Comment by jan-molak** [comment]
Thanks @jbprat! Would you mind pushing the contents of your `target` directory too, so that I can have a look at the `json` files?

**Comment by jbprat** [comment]
@jan-molak I added the target folder to my git repo! ;)

**Comment by jan-molak** [comment]
Thanks! I managed to reproduce the issue, the fix is on the way!

**Comment by jbprat** [comment]
Great!

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by jan-molak** [comment]
The latest version should resolve the problem you've experienced. Please let me know if everything's working OK for you now?
