### ISSUE TITLE
Capabilities tab not showing and Capability showing as a feature

### ISSUE THREAD

**Issue by Baasie** [jan-molak/serenity-js#78]
Just tested this with our own example, but also with the basic journey tutorial.

When I run the example everything goes okey, only the capabilities tabs is not showing, and the capability itself is now showing as a feature:

![image](https://user-images.githubusercontent.com/6578565/29163116-c3e335ce-7dbb-11e7-8a69-054814db073d.png)

**Comment by jan-molak** [comment]
Thanks @Baasie! I'll close this ticket as #75 seems to describe the same issue and has more details.
