### ISSUE TITLE
Duplicate feature name in serenityjs report

### ISSUE THREAD

**Issue by vijay-kumar-singh** [jan-molak/serenity-js#81]
Hi,
I am getting duplicate feature name in serenityjs report.

i have setup project structure in following way:
-features(Folder)
    -profile(folder)
        -profileAccountsDetails.feature(cucumber feature file)
    -otherFeature(folder)
        -otherFeature.feature(cucumber feature file)

And in feature file(profileAccountsDetails.feature):
   Feature: Profile Details
        As a valuable customer,
        I would like to visit Profile page.......
        ...........
After executing i am getting duplicate title in Serenityjs report.
<img width="1017" alt="screen shot 2017-08-11 at 10 15 10 am" src="https://user-images.githubusercontent.com/26203635/29205576-0bc7e0de-7e7e-11e7-9d33-0065d1b8403f.png">

Please suggest how i can remove duplicate feature title here.

Regards,
Vijay Singh

**Comment by Baasie** [comment]
The first profile is the capability, the same issue is probable described here to:
#75

I have the same issues atm

**Comment by jan-molak** [comment]
@Baasie, @vijay-kumar-singh - the latest version should address this issue. Please let me know if it's all working for you now?

**Comment by jan-molak** [comment]
Closing the ticket as the issue should be resolved now.
