### ISSUE TITLE
Error: WebDriverError: java.io.IOException: Error writing to server

### ISSUE THREAD

**Issue by uipoc** [jan-molak/serenity-js#85]
Hi,

Today morning, my automated test script was working fine.
Sudden its start getting failed with following error:
**(node:2414) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): WebDriverError: java.io.IOException: Error writing to server**

(node:2414) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 16)

**Step Definition: node_modules/serenity-js/src/serenity-cucumber/stage_cue.ts:6**
WebDriverError: java.io.IOException: Error writing to server
         at WebDriverError (/Users/...../node_modules/selenium-webdriver/lib/error.js:27:5)
         at Object.checkLegacyResponse (/Users/..../node_modules/selenium-webdriver/lib/error.js:505:15)
     

Please suggest how to fix this issue.
Regards,
Vijay Singh

**Comment by jan-molak** [comment]
Hey @uipoc! What version of Selenium server are you using? Also, are you using a standalone Selenium server jar or a grid?

Thanks,
Jan

**Comment by jan-molak** [comment]
I managed to reproduce the error with Selenium Standalone version 3.5.0. 
Version 3.4.0 doesn't seem to have this problem.

@uipoc, would you be able to run your tests with version 3.4.0?
To install it with webdriver-manager add `versions.stanadlone` to your npm script [as per the instructions](https://github.com/angular/webdriver-manager/blob/master/docs/versions.md):
`webdriver-update --standalone --versions.standalone 3.4.0`

**Comment by uipoc** [comment]
Hi Jan-molak,

I appreciate your help and support.
I have tried updating webdriver version to 3.0.1. But still i am getting same error.
Please see below log and steps which i have done:
**webdriver-manager update --standalone --versions.standalone 3.0.**1
**webdriver-manager status**
webdriver-manager: using global installed version 12.0.6
[11:33:02] I/status - selenium standalone version available: 3.0.1 [last]
[11:33:02] I/status - chromedriver version available: 2.31 [last]
[11:33:02] I/status - geckodriver version available: v0.18.0 [last]
[11:33:02] I/status - android-sdk is not present
[11:33:02] I/status - appium is not present
------------------------------------------------------------------------------------------
following is package.json file config:
{
  "name": "testSerenityjs",
  "version": "0.0.1",
  "description": "Test Automation App",
  "main": "index.js",
  "scripts": {
    "clean": "rimraf target",
    "lint": "tslint --config ./tslint.json --project ./tsconfig.json --format stylish",
    "pretest": "serenity update",
    "pree2e": "npm run lint && npm run webdriver:update -- --standalone --versions.standalone=3.0.1 --versions.chrome=2.29",
    "e2e": "protractor ./protractor.conf.js",
    "report": "serenity run",
    "test": "failsafe clean e2e report",
    "webdriver:update": "webdriver-manager update"
  },
  "repository": {
    "type": "git",
    "url": "xxxxxxx"
  },
  "author": "xxxxxx",
  "license": "SEE LICENSE IN LICENSE.md",
  "dependencies": {},
  "devDependencies": {
    "@types/chai": "4.0.0",
    "@types/chai-as-promised": "0.0.31",
    "@types/cucumber": "1.3.1",
    "@types/node": "7.0.31",
    "chai": "4.0.2",
    "chai-as-promised": "7.0.0",
    "chai-smoothie": "0.x",
    "cucumber": "1.3.2",
    "npm-failsafe": "0.x",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "serenity-cli": ">= 0.4.0",
    "serenity-js": ">= 1.7.0",
    "ts-node": "3.0.6",
    "tslint": "5.4.3",
    "tslint-microsoft-contrib": "5.0.0",
    "typescript": "2.4.0"
  },
  "engines": {
    "node": ">= 6.9.x"
  }
}
---------------------------------------------------------------------------------------
I am using macbook and have done following steps:
update webdriver-manager to version 3.0.1
run npm test
And still see the same issue.

Please suggest a way to fix this issue.

Regards,
Vijay Singh

**Comment by uipoc** [comment]
Hi Jan,

I am able to solve this issue as per your suggestion.
After updating web-driver version using
webdriver-manager update --standalone --versions.standalone 3.0.1
i have deleted node_module package from my project and then run 
npm install 
npm test

it working without any error.
Thanks a lot for your support and help.

Regards,
Vijay Singh

**Comment by jan-molak** [comment]
Not a problem at all, happy to help! 
Would you mind up-voting angular/protractor#4451 so that the root cause is addressed?

Thanks!
Jan
