### ISSUE TITLE
test dom element is visible on screen

### ISSUE THREAD

**Issue by vijay-kumar-singh** [jan-molak/serenity-js#86]
Hi,

I am trying to automate test where i need to get reference of an element which is visible based on different condition.

When i am trying to get element reference when its not available, it throw error like element locator not able to find element. Thats expected but i dont want to get error here, instead need a helper method which return true when element is not available.

i am trying to do something below to get this done:

import { by } from 'protractor';
import { Target } from 'serenity-js/lib/screenplay-protractor';

export class BookingUI {
static Booking_Code_Label = Target.the('Booking Code Label').located(by.css('.bookingcode .key'));
}

and in step definition code:
this.Then(/booking code should not be visible$/, function(details) {
return this.stage.theActorInTheSpotlight().attemptsTo( expect(this.stage.theActorInTheSpotlight().toSee(WebElement.of(BookingUI.Booking_Code_Label))).not.present,
);
});

But i am getting error: 'Property 'present' does not exist on type 'Assertion'.
please suggest if i am doing this right way or any other way to test if any Dom element is present in page in serenityjs way. I am using Cucumberjs with chai-as-promised library for non angular website.

**Comment by jan-molak** [comment]
Hi there!

If you need to [wait for an element](https://github.com/jan-molak/serenity-js/blob/e8155e0499c29570268a701af5849965251220d2/packages/serenity-js/spec/cookbook/waiting.recipe.ts#L112) to become visible before you do something with it, use:

```typescript
actor.attemptsTo(
    Wait.until(BookingUI.Booking_Code_Label, Is.visible())
);
```

However, if you want to _assert_ on a property of an element, use [`See.if`](https://github.com/jan-molak/serenity-js/blob/e8155e0499c29570268a701af5849965251220d2/packages/core/src/screenplay/interactions/see.ts), probably combined with [`chai-smoothie`](https://www.npmjs.com/package/chai-smoothie):

```typescript
actor.attemptsTo(
  See.if(WebElement.of(BookingUI.Booking_Code_Label), el => expect(el).to.eventually.be.displayed),
);
```

Hope that helps!
Jan

**Comment by vijay-kumar-singh** [comment]
Hi Jan,
Thank you for help.
I just tried as per your suggestion. But i am getting error:
Following is my  code:
===================================================
static Booking_Code_Label = Target.the('Booking Code Label').located(by.css('.profile-page .bookingcode .key'));
===================================================
this.Then(/(.*) should not be visible$/, function(details) {
        return this.stage.theActorInTheSpotlight().attemptsTo(
            See.if(WebElement.of(FlyingBlueUI.Booking_Code_Label), el => expect(el).to.eventually.be.displayed),
        );
    }); 
**Error: 
unresolved variable displayed.
features/steps/flyingBlueDetails.steps.ts (73,102): Property 'displayed' does not exist on type 'PromisedAssertion'. (2339)**

Actually i want to just check some Dom element display status based on condition. 
So in one case, i should check Dom element is present and in another case i should check Dom element should not present.
Something like below:
expect( browser.elements( '.someElements' ) ).to.not.exist;

**Comment by jan-molak** [comment]
Hey Vijay,

Property `displayed` comes with the [`chai-smoothie`](https://www.npmjs.com/package/chai-smoothie) I mentioned in my previous post. You'll need to download that module and plug it into Chai to make the `displayed` assertion available, as per [the instructions](https://www.npmjs.com/package/chai-smoothie#setting-up).

Hope that helps,
Jan

**Comment by vijay-kumar-singh** [comment]
Thank you Jan.
I just installed chai-smoothie and tested. 
I believe it just show error in fancy way which in fact does not look like error . Scenario result shows in green but it throw error at last :  NoSuchElementError: No element found using locator: By(css selector, .bookingcode .key)

May be what i am thinking thats not right way. I want to test if Dom Element should not available on screen. But to check this, if i write code like 
static Booking_Code_Label = Target.the('Booking Code Label').located(by.css('.profile-page .bookingcode .key'));
And if above dom reference is not available on page then i should always get 'NoSuchElementError' error at last.

Thank you for help.

Regards,
Vijay

**Comment by AbhineetSharmax** [comment]
Hi Vijay, have you got any workaround for it?
