### ISSUE TITLE
Why all the remaining specs were stopped when one spec got an fail/error message?

### ISSUE THREAD

**Issue by iManinesan** [jan-molak/serenity-js#88]
For an example I specified two specs in protractor configuration like
`  specs: ['test1.spec.ts','test2.spec.ts'],
`

When  test1.spec.ts failed at one point whole process get stopped! why is not running the test2.spec.ts?

**Comment by iManinesan** [comment]
Errrr! Sorry my bad! Thanks a lot!

**Comment by jan-molak** [comment]
No worries, happy to help!
