### ISSUE TITLE
Serenity reports for mocha (without protractor)

### ISSUE THREAD

**Issue by Tech-D** [jan-molak/serenity-js#95]
Hi All,

I am relatively new to world of JS. I am using CHAKRAM to automate rest-api's with mocha. I was wondering if we could use serenity js in someway to generate those beautiful reports. Most of the documentation talks about plugins with protractor to generate JSON reports under target folder. 

It'd be great if there is any demo project out there for REST with serenity js. Appreciate any help!

Thanks,
Darshan

**Comment by jan-molak** [comment]
Hey there! I'm planning to add support for protractor-free tests soon. First, the long-outstanding support for cucumber, then mocha :-) Stay tuned!

**Comment by voidgit** [comment]
Hi Jan,

Are there any plans to integrate Serenity JS with Jest? 

We are planning to test React Native applications on real devices(as one of final stages of CD pipeline). 

Considering:
1. Java, Serenity, Appium
2. Js, Jest, wd, Appium 
3. We really wanted to use Js, Serenity Js, Jest/Mocha/Cucumber, Appium  but Protractor does not support native apps (only hybrid ones). Ideal solution for us seems Js, Serenity Js, Jest, Appium.
4. Checking Detox as alternative (gray box)

Best regards, 
Vadym

**Comment by jan-molak** [comment]
Hi, @voidgit, and thanks for your suggestion. I should be done with Protractor-free mocha integration module shortly, so based on that we could create a Jest-specific module.

Would you mind raising a separate ticket for Jest integration?

Thanks!
Jan

Note to self:
- [custom reporters with Jest](https://facebook.github.io/jest/docs/en/configuration.html#reporters-array-modulename-modulename-options)

**Comment by jan-molak** [comment]
@Tech-D - documentation and examples coming soon!

**Comment by voidgit** [comment]
Hi @jan-molak 

Created new issue (https://github.com/jan-molak/serenity-js/issues/100) for Serenity with Jest.

Sorry for the delay.

Best regards,
Vadym

**Comment by Tech-D** [comment]
@jan-molak thank you for the efforts!

Sorry, I am not able to find documentation / examples. Could you please provide any details around to start things off for mocha without protractor. 

Thanks,
Darshan
