### ISSUE TITLE
RESTAPI automation using serenityjs

### ISSUE THREAD

**Issue by vijay-kumar-singh** [jan-molak/serenity-js#97]
Recently i have used serenityjs with Cucumber and chai to automate my non angular web application developed using Reactjs framework. Its works like charms.
Thank you jan Molak for creating Serenityjs - a beatiful acceptance testing library. 
The great thing is, my automation test is reliable now. when ever i run test it provide exact correct test report. 

Now i am looking forward to do Rest API automation test for my application. and i would like to use Serenityjs for the same. 
I learn that there is a serenity-js core module is available which can be use for automating RestAPI.
But still i am looking forward for any sample small demo application available for RESTAPI automation using serenityjs with Cucumber which can help me to get started.

please suggest.

Thanks in advance.

Regards,
Vijay

**Comment by jhenaoz** [comment]
yes i am looking for any example without the protractor usage, just REST api automation.

**Comment by Baasie** [comment]
https://gitlab.com/Baasie/serenityjs-rest-example

I made an example for rest, @jan-molak gave me the info required to create this.

In the future i will publish an example working with AWS rest gateway and dynamodb. But i think this will be a good start for you ?

**Comment by vijay-kumar-singh** [comment]
Thanks Baasie.

I tried provided example and its works. 👍 
I will be looking more into it and let you know if any thing comes on way.
But for now its look good and i can proceed. 
Thanks again for sharing.

Regards,
Vijay Singh
