### ISSUE TITLE
How to read a text/value from an element?

### ISSUE THREAD

**Issue by iManinesan** [jan-molak/serenity-js#99]
Hi,

I wanna read a text/value from an element and save it on a variable for future usage, now I'm using like this

let text:string;
element(by.id("text")).getText().then(function (txt) {
   text= txt;
});

Is there any way to getText/value inside actor.attemptsTo(...)?

**Comment by jan-molak** [comment]
Hey @iManinesan, you'll need a `Text.of` `Question` to retrieve the text contents of an element and an `Ability` to `TakeNotes` to remember the answer to that question.

You'll find an example of that in the documentation on [Delayed Assertions](http://serenity-js.org/design/assertions.html#delayed-assertions).

Hope this helps!
Jan

**Comment by nizar-nizar** [comment]
this.Then(/^check something$/,function(){
var elemtext: PromiseLike = james.toSee(Text.of(elem));
return elemtext.then(function(val)){
console.log(val);

})
